examples/src/simple.rs
src/linux/process.rs
src/linux/system.rs
src/mac/ffi.rs
src/mac/process.rs
src/mac/system.rs
src/sysinfo.rs

This implements #25 for Linux and Mac OS. It is tested on both platforms (OS X 10.11, Debian 8.6). Looks like there's no testsuite for sysinfo to run this against, correct?

Add parent process id

---

src/linux/system.rs

Remove ":" command splitting in linux

---

src/linux/system.rs

It doesn't make sense to add VSZ to RSS for Process::memory on Linux (I believe this library is using only RSS on Mac). VSZ is just all memory that the process can access, including memory that is swapped out and memory that is from shared libraries.
I have 8 GB total memory on my pc and I am getting more than 64GB memory used if I sum memory of all processes.

Use RSS for Process::memory on Linux

---

src/linux/system.rs

Filter /proc/mounts lines starts with /dev/sd

---

src/linux/system.rs

PathBuf does not implement std::default::Default in older Rust versions.

Compile fix for Rust 1.15.

---

src/linux/disk.rs
src/linux/system.rs

Currently, parsing the CPU time from /proc/stat on our RHEL 6.5 fails with the following error:
`
0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
1: std::sys_common::backtrace::_print
at /checkout/src/libstd/sys_common/backtrace.rs:71
2: std::panicking::default_hook::{{closure}}
at /checkout/src/libstd/sys_common/backtrace.rs:60
at /checkout/src/libstd/panicking.rs:380
3: std::panicking::default_hook
at /checkout/src/libstd/panicking.rs:390
4: std::panicking::rust_panic_with_hook
at /checkout/src/libstd/panicking.rs:611
5: std::panicking::begin_panic_new
at /checkout/src/libstd/panicking.rs:553
6: std::panicking::begin_panic_fmt
at /checkout/src/libstd/panicking.rs:521
7: rust_begin_unwind
at …

[FIX] More robust parsing of /proc/stat

---

Cargo.toml
benches/basic.rs
examples/src/simple.rs
src/linux/system.rs
src/mac/system.rs
src/sysinfo.rs
src/windows/process.rs
src/windows/system.rs
src/windows/tools.rs

Before:
```
test bench_new                ... bench:   6,277,338 ns/iter (+/- 776,626)
test bench_refresh_all        ... bench:   2,777,395 ns/iter (+/- 792,563)
test bench_refresh_disk_lists ... bench:     252,386 ns/iter (+/- 27,681)
test bench_refresh_disks      ... bench:         616 ns/iter (+/- 270)
test bench_refresh_network    ... bench:      44,931 ns/iter (+/- 10,870)
test bench_refresh_process    ... bench:       4,250 ns/iter (+/- 132)
test bench_refresh_processes  ... bench:   1,130,398 ns/iter (+/- 34,410)
test bench_refresh_system     ... bench:     701,725 ns/iter (+/- 167,934)
```
After:
```
test bench_new                ... bench:   3,998,801 ns/iter (+/- 233,505)
test bench_refresh_all        ... bench:   1,278,118 ns/iter (+/- 143,394)
test bench_refresh_disk_lists ... …
```

Performances

---

src/linux/system.rs

This line has been removed in a887677cc2ee01c0a0439139c00afe69ac59ce09 for some reason. It is setting memory correctly now.
Closes: #122

Set entry.memory

---

src/linux/system.rs

This fixes an issue where `sysinfo::get_disks()` would not include any
disks with the `/dev/nvme` prefix. Rather than just checking the
`/proc/mounts` file for `/dev/sd*` disks, we now also check for
`/dev/nvme*` disks.
Closes #131.

Allow for discovering NVMe disks on Linux systems

---

src/traits.rs

Hey,
This is a really useful crate to have!
I figured out that the units memory sizes are reported in are not bytes, but kibibytes. I think that is worth to document.
I also corrected some spelling/grammar.
I hope you find this useful!

Added unit information for `get_*_memory()` methods

---

build.rs

Similar issue to: https://github.com/servo/core-foundation-rs/pull/114
Build scripts are always compiled for the target machine building them. So in cases where you are using a unix CI server with `x86_64-apple-darwin` toolchain the `target_os` is not `macos. Thus it will not add the necessary frameworks and fail compilation.

Properly Support Cross Compilation on Unix

---

Cargo.toml
src/common.rs
src/sysinfo.rs
src/unknown/component.rs
src/unknown/disk.rs
src/unknown/mod.rs
src/unknown/network.rs
src/unknown/process.rs
src/unknown/processor.rs
src/unknown/system.rs
src/utils.rs

Close #179 
Ideally, `get_current_pid()` would return a `Result`, and that would return `Err` when `target_os = "unknown"`. But I didn't do that since that would be a breaking change.

Make it compile on unknown operating system

---

src/linux/system.rs

Raspbian uses root and mmcblk for physical disks. This adds those to the whitelist.

Add disk support for Raspbian 

---

src/linux/process.rs
src/linux/system.rs
src/mac/process.rs
src/mac/system.rs
src/traits.rs
src/unknown/process.rs
src/windows/process.rs

This adds virtual memory usage to Linux / OSX / Windows and changes Windows to use the WorkingSetSize for its resident memory usage stat.
Builds without error on Windows and Linux, however I'm unable to test building on OSX.

Add process virtual memory usage

---

src/windows/processor.rs
src/windows/system.rs

I noticed that InternalQuery never cleans up the handles and counters it's holding so I've added an impl Drop for it. We also had some issues here with the panics in the Windows System impl so I've replaced those with eprintln and only progress further on success.

Replace Windows panic's with print output and make sure that Windows InternalQuery cleans up when dropped

---

Cargo.toml
src/common.rs
src/sysinfo.rs
src/utils.rs

At the moment, `sysinfo` compiles to `wasm32-unknown-unknown`, but not `wasm32-wasi`.  This changes the conditional compilation so that `wasm32-wasi` (and other `wasm32` targets) are supported.

Support `wasm32-wasi` target

---

README.md
examples/src/simple.rs
src/linux/process.rs
src/mac/process.rs
src/sysinfo.rs
src/traits.rs
src/windows/process.rs
src/windows/system.rs

This is about closing issue #239. "KiB" should be the correct unit for everywhere it previously said _kB_, but I have not verified it for `sysinfo::ProcessExt::virtual_memory`.

Replace all "kB" with "KiB"

---

src/linux/network.rs

Outcome should be using TX, but on linux it seems to be using RX right now.

Fix error with networks and total outcome on Linux

---

src/windows/process.rs

Fixes #257.
I simplified the implementation. No more need to have the right on `TERMINATE_PROCESS`.
Can you confirm it works for you @Grindv1k please?

Fix ProcessExt::kill on windows

---

Cargo.toml
src/linux/system.rs
src/windows/process.rs
tests/process.rs

In this PR I implemented those things:
1) Bugfix: in linux cmd() didn't return arguments with length == 1
2) get_cmd_line for windows by ReadProcessMemory
3) cmd() tests. I checked them only in linux and windows.

Get cmd line

---

.travis.yml
src/unknown/component.rs
src/unknown/processor.rs
src/unknown/system.rs

Additionally I have added one more target for Travis script. I'm using `wasm32-unknown-unknow` because I have encountered this problem compiling to that target. Please let me know if I should change anything in this pull request.

Fix compilation for unknown target

---

README.md
src/linux/component.rs

This adds a note on unreliable or missing components when querying virtual Linux systems, due to non-standard `/sys/class/*` support from hosts.
This also corrects a brand name from`Raspberry` to `Raspberry Pi` and grammatical error of `support` to `supports`.

Add note on virtual systems to README

---

src/linux/disk.rs
src/linux/system.rs

Fixes the mis-aslignment between the name inside `/proc/mounts` and `/sys/block` devices. For example, the device `/dev/mapper/fedora_localhost--live-root` is a symbolic link to `/dev/dm-0` and there's no device `fedora_localhost--live-root` under `/sys/block`. Instead find the target of the symbolic link and use the real name.
Also, parses different devices according to their names. For example, when parsing nvme devices, parse the name `nvme0n1p1` to `nvmen1` instead of previous `nvmen1p`.
Closes: https://github.com/GuillaumeGomez/sysinfo/issues/204
Signed-off-by: Allen Bai <carpe.diem.allen@gmail.com>

linux/disk.rs: fix unknown disk type error

---

src/linux/system.rs

Hello,
This PR closes Issue #295, where some disks and file systems were not showing up when calling `get_disks`. Also fixes an [issue](https://github.com/bvaisvil/zenith/issues/28) for zenith.
There were two problems, one `get_all_data_from_file` unexpectedly did not get all of the data. Second, the filter used for `/proc/mounts` filtered out file systems (e.g. ZFS stores) that should have been returned.
Current filter is taken from this [PR](https://github.com/bvaisvil/zenith/pull/26)  to zenith and should probably be evaluated.
Performance with the changes has degraded by at least 2x. Though in my testing at least of some of the performance change was due to an increase in the number disks to create and refresh.
Disks before:
```
Disk("/dev/mapper/fedora-root")[FS: [101, 120, 116, …
```

Fix For Issue 295

---

src/linux/system.rs

We can not assume that the slice always has 5 elements. This rewrites
the code to use `starts_with`.
(Would be nice to get a bug fix release that includes this patch)

Fix out of bound slice access

---

src/linux/system.rs

Hi, this is a patch for the memory info report.
According to `man free`:
> **used**   Used memory (calculated as **total** - **free** - **buffers** - **cache**)

fix memory usage in linux platform

---

src/linux/system.rs

@GuillaumeGomez Sorry for incorrect implementation in my previous PR. I just found there is still a big gap when I compare with the output of `free` command. So I checked out the source code of `procps`,  and fixed it in this PR.
I should be more careful before I submit the previous PR...
The key is `cache` size is the sum of `Cached` and `SReclaimable` in `/proc/meminfo`, but in the previous PR, I assumed `Cached` means `cache`.
> $ man free
> ...
> **used**   Used memory (calculated as total - free - buffers - **cache**)
> ...
> **cache**  Memory used by the page cache and slabs (**Cached** and **SReclaimable** in /proc/meminfo)

Fix memory used calculation

---

src/linux/component.rs

Fix no temperature on Raspberry Pi

---

src/linux/network.rs

The statistics for network interfaces are 64bit numbers on linux, even
if the OS is 32bit. Using usize for theses statistics work only if the
current host has transfered less than 4GB.

Bug: usize on 32bit OS is too small

---

src/windows/processor.rs

There was an error in the parenthesis during the calculation of this constant, fixing this in the downstream projects where it got propagated to. See
https://github.com/giampaolo/psutil/issues/1552
https://github.com/giampaolo/psutil/pull/1583

Fix load average constants on windows

---

src/common.rs
src/linux/disk.rs

Two small modifications:
DiskType::from use the value of /sys/block/<device>/queue/rotational to guess if a mounted device is an SSD
or a HDD.
1 means HDD, and 0 SSD.
Ignore the devtmpfs filesystem, it is the pseudo filesystem used /dev directory.

Bug: right detection of SSD or HDD disk.

---

.travis.yml
src/sysinfo.rs

This adds iOS support, it treats iOS targets as macOS (they act the same)
it builds correctly as a `staticlib` so I guess it would work with no issues.
I also added one of iOS targets to `.travis.yml` so we could test it too.

Add iOS support

---

src/linux/system.rs
src/mac/system.rs
src/traits.rs
src/unknown/system.rs
src/windows/system.rs

Generally, "free" memory refers to unallocated memory and "available"
memory refers to that that is available for (re)use.
Currently, available memory is being reported on Mac and Windows as
"free", whereas only free memory is reported on Linux.
As Windows does not seem to report free memory, with this commit it
continues to report available memory via `get_free_memory`, but the
correct values will be reported on Mac and Linux for both.
References:
Linux: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773
Mac: https://opensource.apple.com/source/xnu/xnu-1504.7.4/osfmk/mach/vm_statistics.h.auto.html
Windows: https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/ns-sysinfoapi-memorystatusex

Add available memory

---

src/mac/component.rs

Current `src/mac/component.rs` defines several CPU temperature sensors. They all work on the (older) MacBooks, but, unfortunately, provide wrong values on the newer iMac (see issue #357).
This PR addresses #357 by adding definition for [Platform Environment Control Interface (PECI)](https://en.wikipedia.org/wiki/Platform_Environment_Control_Interface) CPU sensors that appear to return correct values on all the Mac platforms I've tested them so far.
From the Wiki:
> While previous thermal management technologies have made use of thermal diodes, **PECI instead uses on-die digital thermal sensors (DTS)**. These sensors, after being calibrated at the factory, are able to provide digital data concerning processor temperature information. The PECI bus, allowing access to this data from chipset …

Add PECI CPU temperature sensors work on all Macs

---

src/mac/disk.rs

A simple bug I stumbled upon while trying out the library: it reported an SSD as having over 60 000GB free out of 250GB. (If only.)

Fix disk space reporting on macOS

---

.github/workflows/CI.yml
Cargo.toml
README.md
src/linux/system.rs
src/mac/system.rs
src/sysinfo.rs
src/utils.rs
src/windows/system.rs
src/windows/tools.rs

When the feature is enabled, Rayon and parallel iterators are used.  
When the feature is disabled, std::iter::Iterator is used and operations are sequential.

Add crate::utils::into_iter, which is controlled by a `multithread` feature

---

Cargo.toml
examples/src/simple.rs
src/linux/system.rs
src/sysinfo.rs

@deg4uss3r : Just realized that it was a `vec` and that there was a much simpler way to do it which doesn't require to have the `memchr` dependency in #393. I also realized that I forgot to ask you to add an extra command in the example. And since I forgot to do it for the system name and version, I did the 3 at once. :)
Once this is merged, the next PR will be to upgrade the crate version.

Remove memchr and add more examples

---

src/apple/system.rs
src/linux/processor.rs
src/linux/system.rs
src/traits.rs
src/unknown/system.rs
src/windows/processor.rs
src/windows/system.rs
tests/processor.rs

Follow-up of #408.
@mjarkk: After thinking about it for a while, I think it makes more sense to return `None` instead of `0` when we failed to get the number. At least we make it explicit which makes more sense.

Change return type of SystemExt::get_physical_core_count from "usize" into "Option<usize>"

---

README.md
examples/src/simple.rs
src/apple/system.rs
src/linux/system.rs
src/sysinfo.rs
src/traits.rs
src/unknown/system.rs
src/windows/system.rs

This may not be the best way to go about it, but I'm happy to adjust! 
closes #413 
related #415 
Also during an `xcodebuild test ... iOS` of a project I am working on I cannot confirm this works for iOS can someone help confirm this will return something like `14.3` on iOS?

Split `get_version()` into `get_kernel_version()` and `get_os_version()` [macOS, iOS, Linux]

---

.github/workflows/CI.yml
README.md
src/linux/system.rs

This PR adds support for fetching system property strings on Android.
Two things were modified in the process:
1. The code specific to Android missing `RLIMIT_NOFILE` has been removed. This was fixed [almost a year ago in libc](https://github.com/rust-lang/libc/pull/1746).
2. `SystemExt::get_kernel_version` was rewritten to use the [uname](https://docs.rs/libc/0.2.85/libc/fn.uname.html) syscall instead. Reading from `/proc/version` is not allowed on Android inside the app sandbox by default.
The new code added to fetch values in an Android specific way has been tested on an emulator and physical device via adb:
```
SystemExt::get_host_name(): Some("localhost")
SystemExt::get_os_version(): 
- Emulator: Some("11")
- Physical: Some("10")
SystemExt::get_kernel_version(): 
- Emulator: …
```

Implement Android system information retrieval

---

src/linux/disk.rs

1) Correctly unescape the following sequences as per
https://github.com/torvalds/linux/blob/dd86e7fa07a3ec33c92c957ea7b642c4702516a0/fs/proc_namespace.c#L152 :
' ' becomes \040
'\' becomes \134
'\t' becomes \\011
'\n' becomes \\012
2) Allow /run/media as the mount path as this is often used for
mounts by desktop environments using udisks2.
Signed-off-by: Peter De Schrijver <p2@psychaos.be>

Fix a few issues

---

src/apple/system.rs
src/lib.rs
src/linux/system.rs
src/traits.rs
src/unknown/system.rs
src/windows/system.rs

When running `sysinfo` on Windows `get_os_version` was returning `Windows 10 Pro` which did not match the other OSes (e.g. MacOS returning `11.2` for the latest version). 
This MR adds the method `get_long_os_version()` which gives more detail to the OS version. 
Included in this MR is a better format for the Apple `get_system_info()` function that removed the unsafe `set_len()` in favor of getting the size from the initial system call and trimming the null bytes from the end of the string before returning.
For Windows `ProductName` was moved to the new `get_long_os_version()` (as it fit and was the inspiration for this MR) and for `get_os_version()` I added a way to get `u32` values from the Registry and use `CurrentMajorVersionNumber` and `CurrentMinorVersionNumber`.

Add Get Long OS Version

---

src/apple/processor.rs
tests/processor.rs

In particular, the brand string was showing up with a trailing null for me on
my 2019 MacBook Pro, and the test that I added does fail if you remove the
check that I added.

macos: Check for and remove trailing nulls from sysctl strings

---

src/apple/process.rs
src/linux/process.rs
src/windows/process.rs

Since this is an API change, I'll need to make a big release.

Rename ProcessStatus to_string method to as_str

---

Cargo.toml
src/linux/system.rs

Take over of #452. Original PR explanations:
Per [os-release](https://www.linux.org/docs/man5/os-release.html), the VERSION_ID field is not required.
This adds a fallback using `/etc/lsb-release` for systems that do not have a VERSION_ID in the `/etc/os-release` file (such as my Manjaro dist).
Updated the `get_system_info` function to take a `BufRead` to make testing this fallback possible.

Add `/etc/lsb-release` fallback when calculating OS version

---

src/apple/users.rs
src/linux/system.rs

* In local testing, all of the users external to the system came back with UIDs much larger that 65535.  I added to the filter this UID value as a max as it did restrict to local users only.
I'm not sure this value is universal for all `opendirectoryd` UID values, but it's a start.   Also, should this be made configurable?

Attempt to restrict `getpwent` results on MacOS to local users

---

examples/src/simple.rs
src/traits.rs
src/windows/process.rs

Taking over #462.
Part of #459.
@sebipincha: For now I'll just take your CPU usage computation improvement (kept your commit). I'm pretty sure there is a way to avoid the bad CPU usage computation without forcing to wait 500ms between each computation.
In any case, this is already a nice improvement!

Fix cpu usage windows

---

src/linux/system.rs

refresh_process(pid) is called for the first time, the linux implementation returns false when a process is not cached which is incorrect.
compare that with the mac and windows version which returns true.
windows: https://github.com/GuillaumeGomez/sysinfo/blob/58b31e3a5d2821fb0483125220331b3afab5cd11/src/windows/system.rs#L190
mac: https://github.com/GuillaumeGomez/sysinfo/blob/58b31e3a5d2821fb0483125220331b3afab5cd11/src/apple/system.rs#L326
linux: https://github.com/GuillaumeGomez/sysinfo/blob/c3f76b74a614cc8de552c306dc9a00f35977994e/src/linux/system.rs#L351

Fix bug in linux's refresh_process()

---

.github/workflows/CI.yml
src/c_interface.rs

```
[dvaneeden@dve-carbon sysinfo]$ git status
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean
[dvaneeden@dve-carbon sysinfo]$ git describe --always
8165447
[dvaneeden@dve-carbon sysinfo]$ make
Compiling in debug mode
cargo build --features=c-interface
Compiling sysinfo v0.17.2 (/home/dvaneeden/dev/sysinfo)
error[E0432]: unresolved imports `NetworkExt`, `NetworksExt`, `Process`, `ProcessExt`, `ProcessorExt`, `System`, `SystemExt`
--> src/c_interface.rs:10:6
|
10 | use {NetworkExt, NetworksExt, Process, ProcessExt, ProcessorExt, System, SystemExt};
|      ^^^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^  ^^^^^^^^^^  ^^^^^^^^^^^^  ^^^^^^  ^^^^^^^^^ no external crate `SystemExt`
|      |           |            |        |           |             |
| …
```

c_interface: Fix compiling of the C interface

---

src/linux/network.rs

Fixes https://github.com/GuillaumeGomez/sysinfo/issues/479
This removes interfaces that are not longer present in `refresh_networks_list` for Linux, before doing a second pass to update stats or add new interfaces.
I wanted to use `drain_filter` but this is a nightly only API for now.

Linux: Cleanup removed interfaces in refresh_networks_list (fixes #479)

---

src/apple/network.rs
src/linux/network.rs
src/windows/network.rs

Fixes #483.
Mac was using the same logic as linux so I just cleaned it up a bit.
Windows however was using another strategy: it was filling a `HashSet` with the interfaces' key and removed them when it updated one. Then at the end, it removed all the interfaces which still had their key in the `HashSet` at the end. It was really not great because it meant that we duplicated the keys for all interfaces.

Improve network code

---

src/apple/processor.rs

Closes #496 
This patch fixes the bug where on Apple M1 machines, calling `cpu.get_brand()` returns an empty string.
It looks like the real source of this bug was that `get_vendor_id_and_brand()` was returning `(brand_string, vendor_id)` when the result would be stored as `(vendor_id, brand)`. Just reversing the result tuple to match the function name fixed the issue.
It looks like this function is only being called in this file anyway, so shouldn't affect anyone else.

Fix cpu.get_brand() returning empty string on M1

---

examples/simple.rs
src/linux/system.rs

Currently, there is no frequency set for `global_processor` for linux.
This results in my project [sysit](https://github.com/crodjer/sysit) rendering `0` for CPU Frequency on my Raspberry Pi.
I couldn't find the best heuristic to use for global processor
frequency. So using `max` to signify currently the most interesting core.

Ensure there's a value in linux `global_processor`

---

src/windows/process.rs

Prevents the taskkill.exe console windows from appearing.

Add `CREATE_NO_WINDOW` flag for Windows process kill method

---

src/windows/system.rs

This MR changes the windows backend to only create the `Query` (which calls PDH) when refreshing CPU usage.
Motivation: I'm working on a somewhat security-sensitive software, using `sysinfo` to get some information about running processes, their resource usage and so on. This software needs to be resilient against DLL hijacking attacks and other code injection techniques, even against administrators, for various reasons.
In this context, `PDH.dll` is somewhat problematic: it loads the Performance Counter DLLs (which may be registered by anyone) at runtime, which may be used to inject code in my program. Those DLLs are loaded as soon as `PdhAddEnglishCounter` are called.
My program doesn't need system CPU usage, and I don't request it as part of the `RefreshKind`, so building the query …

Lazily create query

---

.cirrus.yml
Cargo.toml
examples/simple.rs
src/apple/system.rs
src/common.rs
src/freebsd/component.rs
src/freebsd/disk.rs
src/freebsd/mod.rs
src/freebsd/network.rs
src/freebsd/process.rs
src/freebsd/processor.rs
src/freebsd/system.rs
src/freebsd/utils.rs
src/lib.rs
src/linux/process.rs
src/linux/system.rs
src/traits.rs
src/users.rs
src/utils.rs
tests/process.rs

Fixes #433.
Only the disk support is missing and then it'll be ready. But we need https://github.com/rust-lang/libc/pull/2565 to be merged first (and a new `libc` release).

Add freebsd support

---

src/apple/app_store/process.rs
src/apple/macos/process.rs
src/apple/system.rs
src/freebsd/process.rs
src/freebsd/system.rs
src/lib.rs
src/linux/process.rs
src/linux/system.rs
src/macros.rs
src/traits.rs
src/unknown/process.rs
src/unknown/system.rs
src/windows/process.rs
src/windows/system.rs
tests/code_checkers/headers.rs
tests/code_checkers/mod.rs
tests/code_checkers/signals.rs
tests/code_checkers/utils.rs

Remains to be done: add a `#[test]` which checks how `kill_with` and `SUPPORTED_SIGNALS` are declared.

Add SUPPORTED_SIGNALS constant on SystemExt

---

src/freebsd/disk.rs

Fixes #668.
@jbeich: I'll try to check how to have a CI check for that as well. In the meantime, can you confirm it's fixing your issue please?

Fix type error for 32-bit freebsd (on i386, armv6, armv7, powerpc)

---

src/common.rs

sysinfo provides a way of getting process(es) by name and other useful utility functions. But, to do anything useful with the Pid, like calling OS functions on it, one must get the raw OS representation of the Pid.
This PR will allow users of the crate to access the newtype field or transmute it soundly.

Make Pid newtype public for getting raw OS pid

---

src/common.rs

This is a backward-compatible change, as there is a blanket `impl<FROM, TO> Into<TO> for FROM where TO: From<FROM>` in the standard library.
This shouldn't cause any issue as far as I can tell. The comment seems to indicate some sort of issue without pointing to any test or issue.
Having a From implementation makes it easier to use in a more complex conversion, e.g. `usize::from(pid) as u32`. With the current code, this must be written as `Into::<usize>::into(pid) as u32`, which is much more verbose.

Impl From<Pid> for usize

---

src/windows/process.rs

Fixes #716 
Also worth considering if `1` would be a better default than `0`

Fix underflow for windows run_time computation

---

src/apple/macos/disk.rs
src/apple/utils.rs

With 0.23.7 (more specifically, with [this change](https://github.com/GuillaumeGomez/sysinfo/pull/714)), I noticed a behavior change in one of my applications where the system disk would not be found by `sysinfo` anymore. The only disk I'd find with `list_disks` was `iSCPreboot`, with a capacity of ~500mb.
By comparing with 0.23.6, I noticed that my application previously relied on the SSV (`com.apple.os.update-[...]`), which is a snapshot volume and is now excluded from detected disks with 0.23.7.
I understood why my snapshot was being excluded, but I didn't understand why my other disks weren't detected, so I dug around and found that my disks were found by `getfsstat` but were subsequently excluded by `get_str_value` because they allegedly did not have a value for the `DAMediaName` …

macOS: Fix disks missing due to incorrect CFStringGetStringPtr usage

---

src/traits.rs

Fix a typo in documentation

---

src/apple/process.rs
src/common.rs
src/linux/disk.rs
src/linux/process.rs
src/linux/system.rs

It seems that divising the virtual memory by the `page_size_in_kb` is necessary to have `kb` and not `bytes` for the virtual_memory. 
Virtual memory and Residual memory do not share the same metric on my machine at the moment.

divising the virtual memory by 1000 to get kb in Linux

---

benches/basic.rs
src/linux/process.rs

With the bench it gives:
```
before:
test bench_first_refresh_processes ... bench:  20,298,159 ns/iter (+/- 1,598,495)
after:
test bench_first_refresh_processes ... bench:  17,830,218 ns/iter (+/- 1,214,291)
```

Improve linux process user ID retrieval

---

src/windows/process.rs

Fixes #771
If opening a process with PROCESS_QUERY_INFORMATION | PROCESS_VM_READ fails the code reverts to using PROCESS_QUERY_LIMITED_INFORMATION. Certain fields may not be available in this case(such as process params) but this is already the case when using refresh_processes().

Attempt to open Windows process with limited access if elevated access fails

---

src/apple/macos/process.rs

There are two problems:
+  a great chance return 0 when call `libc::proc_pidinfo` with `libc::PROC_PIDTHREADINFO` on mac m1
+ refresh process in a very short interval will set `Process.cpu_usage` to 0

fix cpu_usage return 0 on mac m1

---

src/windows/system.rs

That's a fixup of 87773f69e3a128d3071d9d1702fc127083adf72e, which introduced a wrong operation order

fix: fixed Windows boot time

---

src/linux/system.rs

When trying to refresh the CPUs information, I noticed that even I specifically asked for refreshing the frequencies, it didn't work under Linux (frequencies stayed unchanged).
I simply changed a condition which seemed to be the problem in `src/linux/system.rs` and the refresh mechanism now works as expected.
Here is some example code that wasn't working and now works:
```rust
let mut sys = System::new_with_specifics(RefreshKind::new().with_cpu(CpuRefreshKind::everything()));
loop {
thread::sleep(Duration::from_millis(200));
sys.refresh_cpu();
println!("{:#?}", sys.cpus());
}
```

Fixing refreshing CPU frequency under Linux

---

src/lib.rs
src/traits.rs

Changing the behaviour of `refresh_cpu` to disable refreshing CPU frequency.

Don't get cpu frequency by default when using refresh_cpu

---

src/linux/process.rs
src/traits.rs

This PR implements the changes discussed in https://github.com/GuillaumeGomez/sysinfo/issues/697, and publicly documents them as well.
Closes https://github.com/GuillaumeGomez/sysinfo/issues/697

Do not fallback to cmd[0] if /proc/pid/exe is unreadable

---

src/windows/process.rs
tests/process.rs

Some processes (such as svchost.exe) will cause `EnumProcessModulesEx` to fail, even when run with administrator privileges:
The official Microsoft documentation states that the `hModule` parameter of the `GetModuleFileNameExW` function can be NULL to get the path to the executable file: <https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmodulefilenameexw>.
> [in, optional] hModule
> 
> A handle to the module. If this parameter is NULL, GetModuleFileNameEx returns the path of the executable file of the process specified in hProcess.

Fix the problem that Process::exe() sometimes returns an empty PathBuf under windows

---

.github/workflows/CI.yml
src/windows/process.rs
src/windows/system.rs

Fix PID owner change on Windows

---

src/apple/macos/component/arm.rs
src/apple/macos/component/mod.rs
src/apple/macos/component/x86.rs
src/apple/macos/disk.rs
src/apple/macos/ffi.rs
src/apple/macos/mod.rs
src/apple/mod.rs
src/apple/system.rs
src/lib.rs

Hi, I trying to help with this issue #456, and it almost work, but I am a newbie to rust and not familiar with MacOS development. 
when I run the code on my m1 mac, I got 63 sensors' value, but some of  are duplicated, like there are 4  sensors with name `PMU tdie1`, and I do not known if it is right, so I need some help with this. 
```shell
PMU tdie10: 39.083206°C (max: 0°C)
PMU tdie7: 39.260803°C (max: 0°C)
PMU TP2s: 38.9944°C (max: 0°C)
NAND CH0 temp: 35°C (max: 0°C)
PMU tdev1: 37.094604°C (max: 0°C)
PMU tdie10: 38.816803°C (max: 0°C)
PMU TP3g: 39.172012°C (max: 0°C)
PMU tdev4: 35.31082°C (max: 0°C)
PMU TP2s: 39.260803°C (max: 0°C)
PMU tdev7: 37.319824°C (max: 0°C)
PMU TP3g: 38.9944°C (max: 0°C)
PMU tdev4: 35.391907°C (max: 0°C)
PMU tdie2: 39.083206°C (max: 0°C)
PMU tdev7: 38.099106°C …
```

Add support for get temperature on m1

---

src/apple/macos/disk.rs
src/apple/macos/ffi.rs
src/apple/macos/mod.rs
src/apple/macos/utils.rs
src/apple/system.rs

Fixes #811.
I tested with:
```
RUSTFLAGS=-Zsanitizer=address cargo run -Zbuild-std --target x86_64-apple-darwin --example simple
RUSTFLAGS=-Zsanitizer=leak cargo run -Zbuild-std --target x86_64-apple-darwin --example simple
```
@simrankedia: Do you still have the leak with this patch? If so, please tell me what command line you used so I can reproduce it locally.

Fix leak in macOS disk retrieval

---

src/apple/macos/component/arm.rs

Fix #816 
I don't know why the client from this API(`IOHIDEventSystemClientCreate`) is auto released(that's why I create the client every time refresh the components)
so I manually retain the client, it seems fix the segmentation fault

Fix segfault on m1

---

src/linux/process.rs
tests/code_checkers/docs.rs

Strangely `cargo clippy` gave me nothing but `cargo clippy --fix` had some suggestion O_o.

clippy --fix pass

---

src/linux/component.rs
src/linux/disk.rs
src/linux/process.rs
src/traits.rs
tests/code_checkers/docs.rs

May supplant #823, may help in #826.
- Pro: Read more
- cons: refactoring, do some magic to comply with `Component`/`ComponentExt` traits (`labels` and `max`)
Read things that are not used now, maybe doing a Linux specific Hwmon richer trait?
Not exhaustive checklist of what is done:

Read more temperature data from hwmon on linux

---

.cirrus.yml
.github/workflows/CI.yml
CHANGELOG.md
Cargo.toml
README.md

`once_cell` updated its MSRV so we need to update it in `sysinfo` too. Interesting discussion about it is [here](https://github.com/matklad/once_cell/issues/201).

Update MSRV and update crate version to 0.26.3

---

src/apple/system.rs
src/freebsd/system.rs
src/lib.rs
src/linux/system.rs
src/traits.rs
src/unknown/system.rs
src/windows/system.rs

SystemExt::name() returns human-readable distribution name, but there is no machine-readable alternative.
SystemExt::distribution_id() returns os-release.ID, or std::env::consts::OS if os-release.ID is unavailable. Fallback behaviour is consistent with the os-release.ID specification on Linux.
See also
- https://www.freedesktop.org/software/systemd/man/os-release.html#ID=
- https://doc.rust-lang.org/std/env/consts/constant.OS.html
Closes #843.

Add SystemExt::distribution_id()

---

src/utils.rs

That combination is nonsensical, of course, but [it isn't currently possible to enable features only on specific targets][cargo-1197], so any project that targets both Linux and sandboxed macOS will currently fail to build on Linux.
[cargo-1197]: https://github.com/rust-lang/cargo/issues/1197

Fix a compile error on Linux if the `apple-sandbox` feature is enabled

---

src/traits.rs

Adds warnings to the docs that linux process names are limited to 15 characters.

added linux warning

---

src/linux/system.rs

Use MemTotal - MemAvailable for used memory calculation when possible and fallback to the old way of estimating available memory.
Some references:
- https://bugzilla.gnome.org/show_bug.cgi?id=727543
- https://github.com/KittyKatt/screenFetch/issues/386#issuecomment-249312716
- https://github.com/htop-dev/htop/issues/281

More precise used memory calculation on Linux

---

md_doc/disk.md
src/linux/disk.rs

This PR tries to fix the problem that [calling `statvfs` on nfs may hang](https://github.com/GuillaumeGomez/sysinfo/issues/842). It is done by ignoring the fs having its type named `nfs` or `nfs4`.
Avoiding to call `statvfs` on nfs will leave `total_space` and `available_space` to be zeros and can be misleading. So I decide not to include nfs in what returns from `get_all_disks_inner`

Ignore nfs on linux

---

md_doc/disk.md
src/linux/utils.rs
src/traits.rs

@kayoch1n: I moved the documentation directly on the `refresh_disks_list` method. I think it makes more sense this way.

Update documentation location for linux NFS disk handling

---

src/traits.rs

It looks like `System::new` no longer forces refreshing of CPU list. As far as I can tell, this was done in https://github.com/GuillaumeGomez/sysinfo/commit/da1c65c1e34fa2a4bbee441a1616613423217037. 
Thanks!

doc: update `System::new` document to reflect not loading cpus list by default

---

src/network_helper_nix.rs

I ran into a segfault in parse_interface_address, after some debugging I concluded the following.
1. The segfault was caused by ifa_addr being null.
2. ifa_addr being null is documented as a possibility in the getifaddr man page.
3. Specifically, on my linux 4.19 system this happens for "tun" interfaces which do not have a MAC address. 
This pull request makes the function return null if ifa_addr is null.

Fix null pointer dereference in parse_interface_address.

---

src/apple/macos/ffi.rs

Part of https://github.com/GuillaumeGomez/sysinfo/issues/899.

Fix deprecation for kIOMasterPortDefault by turning it into a constant

---

src/traits.rs
tests/process.rs

For these two functions, the lifetime of the returned process is currently coerced into being the smaller lifetime of either the System or the &str. This works fine when the System's lifetime is shorter than the &str, but creates errors when you do things like:
```rs
let process = system.processes_by_exact_name(&String::from("str")).next().unwrap();
```
This can be fixed by changing the bounds to say that the iterator needs to live as long as the System and &str, but the returned Process reference only needs to live as long as the System.

Fix processes_by_name(_exact) lifetimes

---

src/apple/system.rs

Previously, we counted wired memory as available, which is incorrect; wired memory is memory that cannot be evicted from RAM to swap [0]. Looking over the definitions of the available counters, I came up with these simplified calculations for available and free memory, which happily line up with the calculations used in a sister rust crate, `sys-info` [1].
[0]: https://developer.apple.com/library/archive/documentation/Performance/Conceptual/ManagingMemory/Articles/AboutMemory.html
[1]: https://github.com/FillZpp/sys-info-rs/blob/60ecf1470a5b7c90242f429934a3bacb6023ec4d/c/darwin.c#L134-L135

Use more consistent definition for free/avail memory on Darwin

---

src/linux/system.rs

In a future release of the `libc` crate, `libc::timespec` will contain private padding fields on `*-linux-musl` targets and so the struct will no longer be able to be created using the literal initialization syntax.
Update the use of `libc::timespec` to create a value by calling `std::mem::zeroed()` which works with both current versions of `libc` as well as the future version which contains that change.
See also https://github.com/rust-lang/libc/pull/2088

Update use of `libc::timespec` to prepare for future libc version

---

src/linux/cpu.rs

On ARM, Linux only obtains two numbers for CPU implementer and part, there is no marketing name encoded in the cpuid like on x86.  This means we have to interpret those numbers ourselves.
The list of CPU brands and names have been obtained from util-linux, see https://github.com/util-linux/util-linux/blob/master/sys-utils/lscpu-arm.c
The CPU usage and frequency are still completely wrong though.

Add brand and name of ARM CPUs on Linux

---

src/linux/cpu.rs

Follow-up of https://github.com/GuillaumeGomez/sysinfo/pull/914.

Linux: Default to "model name" value if the CPU brand cannot be retrieved

---

Cargo.toml
Makefile

Clients who want a cdylib (including C clients) can use `cargo rustc --crate-type cdylib` to override the default crate-type.
Fixes #932, see there for more explanation.

Remove cdylib crate-type

---

src/apple/macos/system.rs

Seems to be one way to fix the issue highlighted in #956 due to `timebase_to_ns` differing between ARM and x86. From my experience, this has effectively no effect on x86 since `timebase_to_ns` is normally just 1 on that platform.
Tested on my M1 Macbook Pro and an x86 macOS emulator to both be close to `htop` when used to compile `process-viewer`.

hoist out timebase_to_ns in process interval calculation to fix CPU usage calculation

---

src/apple/disk.rs
src/apple/macos/disk.rs
src/common.rs
src/debug.rs
src/freebsd/disk.rs
src/lib.rs
src/linux/disk.rs
src/serde.rs
src/traits.rs
src/unknown/disk.rs
src/windows/disk.rs

A cosmetic change, but a breaking one also.
The underscore at the end of `type_` has bothered for some time now. Maybe using a proximate synonym could be better?

rename public DiskExt method `type_` to `kind`

---

src/apple/macos/process.rs
src/apple/process.rs
src/common.rs

Correctly handle process status on macOS

---

src/apple/app_store/process.rs
src/apple/macos/process.rs
src/freebsd/process.rs
src/linux/process.rs
src/traits.rs
src/unknown/process.rs
src/windows/process.rs
tests/process.rs

Add API to query effective IDs of a process and make `Process::{user_id, group_id}` return real IDs on Linux and Apple, so the behavior is as expected and consistent with the FreeBSD implementation.
Fixes #970.
---
Zeeshan Ali Khan on behalf of MBition GmbH.
[Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md#mbition-gmbh).

Add Process::{effective_user_id, effective_group_id} + user_id & group_id to return real IDs

---

src/windows/system.rs

Part of https://github.com/GuillaumeGomez/sysinfo/issues/1009.
Thanks for the extra explanations @LunNova!

Windows: Remove undefined behaviour when retrieving processes

---

src/windows/system.rs

Fix more UB in windows/system refresh_processes_specifics

---

README.md
src/lib.rs
src/windows/process.rs
src/windows/system.rs

Windows: Get process name using `NtQuerySystemInformation`

---

src/apple/cpu.rs
src/apple/macos/component/x86.rs
src/apple/macos/cpu.rs
src/apple/macos/ffi.rs
src/apple/macos/mod.rs
src/apple/system.rs

Fixes https://github.com/GuillaumeGomez/sysinfo/issues/872.
How to test it:
```
$ cargo run --example simple
Running `target/debug/examples/simple`
Getting processes' information...
Done.
To get the commands' list, enter 'help'.
> refresh
Getting processes' information...
Done.
> frequency
2200 MHz
>
```
If "frequency" returns something on mac M1, it means the PR fixed the issue.

Get CPU frequency on mac M1

---

src/windows/process.rs

- fix: zero init image name memory to avoid leftoverdata interfering
- fix: ImageName.Length is in bytes, we want the size in wide-chars
Use the following:
```rust
use std::process::Command;
use sysinfo::{Pid, PidExt, ProcessExt, System, SystemExt};
fn main() {
let mut ping_process = Command::new(r"C:\Windows\System32\PiNg.eXE")
.args(["-n", "50", "127.0.0.1"])
.stdout(std::process::Stdio::null())
.spawn()
.unwrap();
let ping_id = ping_process.id();
// For some reason, on my VM, retrieving the process too quickly will lead to
// "process.name()" being empty. To avoid this, retry until the process has a name.
loop {
let mut system = System::default();
system.refresh_process_specifics(Pid::from_u32(ping_id), Default::default());
let proc = system.process(Pid::from_u32(ping_id)).unwrap();
if …
```

Fix: windows process name in 0.29.6 are broken

---

src/linux/system.rs

This solves the newline issue I described in #954, though the disk issue probably remains (and the memory issue might also remain specifically for LXC, I don't know how it sets up its cgroups).

Fix cgroups always being ignored when refreshing memory

---

src/windows/users.rs
src/windows/utils.rs

As nicely pointed out [here](https://github.com/GuillaumeGomez/sysinfo/pull/950#issuecomment-1732376879), `sysinfo` was using pointers without checking if they were NULL first.
cc @poliorcetics

Windows: Fix invalid use of NULL pointer

---

src/unix/apple/disk.rs
src/unix/apple/users.rs
src/unix/apple/utils.rs
src/unix/mod.rs
src/unix/network_helper.rs
src/unix/users.rs
src/unix/utils.rs

Part of https://github.com/GuillaumeGomez/sysinfo/issues/1052.

Add missing checks for NULL pointers

---

src/serde.rs

Some of the serializers used incorrect (too small) field counts when serializing structures. This commit/PR fixes that.
This is not an issue when using JSON serializer which doesn't need the length field to operate correctly [0] but it could be an issue if a different serializer would be used in the future which would rely on the length field [1].
[0] https://github.com/serde-rs/json/blob/b6e113f2036c52e994ca805e530ee4ffae791f71/src/value/ser.rs#L262-L277
[1] https://grep.app/search?q=fn%20serialize_map%28self%2C%20len%3A%20Option%3Cusize%3E%29%20-%3E%20Result%3CSelf%3A%3ASerial

serde.rs: fix serialize_struct field counts

---

examples/simple.rs
src/unix/linux/cpu.rs
tests/cpu.rs

Follow-up of #1075 which wrongly updated this information.

Allow to only refresh CPU info in example and correctly parse /proc/cpuinfo file

---

examples/simple.c
src/c_interface.rs
src/sysinfo.h

- fixed: build c interface failed on Windows
- add: some functions to get basics OS&CPU information

add basics os&cpu information to C interface and example

---

README.md
benches/basic.rs
examples/simple.rs
src/c_interface.rs
src/common.rs
src/lib.rs
src/traits.rs
src/unix/apple/disk.rs
src/unix/apple/mod.rs
src/unix/freebsd/disk.rs
src/unix/freebsd/mod.rs
src/unix/linux/disk.rs
src/unix/linux/mod.rs
src/unix/mod.rs
src/unknown/disk.rs
src/unknown/mod.rs
src/windows/disk.rs
src/windows/mod.rs
tests/disk_list.rs

Remove DisksExt trait

---

README.md
benches/basic.rs
examples/simple.rs
src/c_interface.rs
src/common.rs
src/debug.rs
src/lib.rs
src/serde.rs
src/traits.rs
src/unix/apple/app_store/component.rs
src/unix/apple/macos/component/arm.rs
src/unix/apple/macos/component/x86.rs
src/unix/apple/mod.rs
src/unix/apple/network.rs
src/unix/freebsd/component.rs
src/unix/freebsd/mod.rs
src/unix/freebsd/network.rs
src/unix/linux/component.rs
src/unix/linux/mod.rs
src/unix/linux/network.rs
src/unknown/component.rs
src/unknown/mod.rs
src/unknown/network.rs
src/windows/component.rs
src/windows/mod.rs
src/windows/network.rs
tests/network.rs

Remove ComponentExt and NetworksExt traits

---

src/windows/process.rs
src/windows/system.rs
tests/process.rs

The first time a process is refreshed on windows, its memory values are not fetched. This is only done on a second refresh.
Fix this my moving the refresh memory into the process update function so that it is called
everytime the process is updated.
Fixes #1084

fix: refresh process memory on Windows on first update

---

md_doc/pid.md
src/common.rs
src/lib.rs
src/serde.rs
src/system.rs
src/windows/process.rs
tests/process.rs

Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1088.

Remove `PidExt` trait

---

src/common.rs

Add missing warning for Windows support for `System::load_average`

---

src/common.rs

Implement `IntoIterator` for `Disks`, `Components` and `Users` types

---

src/windows/disk.rs

This PR changes the mechanism for enumerating "disks" on windows. The previous approach only worked for volumes that were assigned a drive letter. Windows volumes can also be mounted in the file system.
We first fetch a list of volume GUID paths (volume names). These have the form `\\?\{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}\`. We then use `GetVolumePathNamesForVolumeNameW` to map each of these to a set of mount paths (`C:\` for drive letters or arbitrary paths for path mounts). We then return one `Disk` entry for each mount path (flat-map).
This should roughly match the semantics of the linux implementation, which also primarily looks at mount points (not actual disk volumes). It means that a volume that is mounted multiple times (multiple drive letters and/or mount paths) will show up as …

win: enumerate drives via FindNextVolumeW + GetVolumePathNamesForVolumeNameW

---

src/common.rs
src/debug.rs
src/unix/apple/disk.rs
src/unix/freebsd/disk.rs
src/unix/linux/disk.rs
src/unknown/disk.rs
src/windows/disk.rs

As discussed in #1105, this PR changes the public interface `Disk::file_system()` to return an `&OsStr` instead of a `&[u8]`.
(I've decided to move the MSRV change into a separate PR #1108 because there is really no connection between these two PRs)

Change `Disk::file_system()` to return `&OsStr`

---

src/common.rs
src/lib.rs
src/serde.rs
src/unix/apple/system.rs
src/unix/freebsd/system.rs
src/unix/linux/system.rs
src/unknown/system.rs
src/windows/system.rs

Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1071.

Move cgroup limits computation into its own function to split it out from the "normal" memory values

---

src/common.rs
src/lib.rs
src/unix/apple/macos/process.rs
src/unix/freebsd/process.rs
src/unix/freebsd/system.rs
src/unix/linux/process.rs
src/windows/process.rs
src/windows/system.rs
tests/process.rs

Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1016.

Extend `ProcessRefreshKind` to allow more specific updates

---

src/lib.rs
src/unix/linux/system.rs
src/unix/linux/utils.rs

This removes some unsafe code and a clippy allow, I used the strongest Ordering (`SeqCst`) when the operation ordering mattered and used `Relaxed` when it doesn't, although could swap it to `SeqCst` if you want.

Replace REMAINING_FILES static mut with Atomic

---

Cargo.toml
src/common.rs
src/unix/linux/disk.rs

This brings NFS back, but only as an optional feature called `netdevs`.
Why `netdevs`? Because when CIFS is mounted with the **hard** option, it would cause the same hang as NFS. The only difference is that NFS is hard by default and CIFS is soft by default. So in my option it makes more sense to disable both by default, but enable them with feature if users have no problem with the risk.
More details about the issues with mounting NFS: https://github.com/GuillaumeGomez/sysinfo/issues/842#issuecomment-1815859527

add the netdevs feature for the optional bring back of NFS

---

src/unix/users.rs
src/windows/cpu.rs
src/windows/system.rs
src/windows/utils.rs

Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1149.

Correctly handle `Vec::reserve`

---

src/users.rs

Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1154.
In the new version, the code has been re-written and the check is already in place, so nothing to do for 0.30.

Correctly handle where group name is NULL

---

src/common.rs
tests/process.rs

Get `Process::exe` information by default

---

src/c_interface.rs
src/common.rs
src/unix/apple/app_store/process.rs
src/unix/apple/macos/process.rs
src/unix/freebsd/process.rs
src/unix/freebsd/system.rs
src/unix/linux/process.rs
src/unix/linux/utils.rs
src/unknown/process.rs
src/windows/process.rs
tests/process.rs

Make `Process::exe`, `Process::cwd` and `Process::root` return an `Option<&Path>`

---

src/c_interface.rs
src/common.rs
src/sysinfo.h
src/unix/linux/process.rs
tests/process.rs

Follow-up of https://github.com/GuillaumeGomez/sysinfo/pull/1168.

Make Process::tasks method available on all platforms and change its return type to `Option`

---

src/common.rs
src/unix/apple/system.rs
src/unix/freebsd/system.rs
src/unix/linux/process.rs
src/unix/linux/system.rs
src/unknown/system.rs
src/windows/system.rs
tests/process.rs

Add `System::refresh_pids` and `System::refresh_pids_specifics` methods

---

src/unix/linux/process.rs

The new get_memory function for linux mixes up total memory and resident memory, see [proc(5)](https://man7.org/linux/man-pages/man5/proc.5.html).

first column in statm is total size, second column is resident set size

---

src/windows/process.rs
src/windows/system.rs

Targetting `i686-pc-windows`, an initial try to fix #1188 which led to:
– A dead-end regarding this fix (because a 32-bit process can’t read 64-bits process memory… For obvious reasons 😅)
– A fix in `Process.name()` whose buffer length was too short
– A fix in swap memory computation, not using `usize` but extending to `u64` (because even on 32-bit platforms, memory can be big 😉).

Fixes for Process.name() and swap memory computation on i686-pc-windows-msvc

---

README.md
src/common.rs

Improve documentation

---

src/unix/apple/macos/process.rs

While doing some testing with sysinfo, I found out that run_time is not being updated when refresh is called.

Bugfix: Update `run_time` for MacOS processes during refresh

---

src/common.rs

During testing on FreeBSD, I found that `disk_usage()` only measures disk read/writes. This makes sense, since sysutil uses `getrusage`, and the [man page](https://man.freebsd.org/cgi/man.cgi?query=getrusage) clearly indicates that `ru_inblock` and `ru_oublock` represent disk I/O. Not sure where the comment about measuring all I/O comes from.

Correct comment about `disk_usage()` in FreeBSD

---

src/unix/linux/system.rs

Remove memory stat code from cgroup mem calculation

---

.cirrus.yml
.github/workflows/CI.yml
Cargo.lock
Cargo.toml
README.md
migration_guide.md
src/lib.rs
src/unix/linux/system.rs
src/unix/linux/utils.rs
src/unix/network_helper.rs
src/windows/cpu.rs
src/windows/process.rs

- replace once_cell::sync::Lazy into std::sync::OnceLock 
- increase MSRV to 1.70.
fix https://github.com/GuillaumeGomez/sysinfo/issues/1217

remove once_cell and increase MSRV to 1.70

---

Cargo.toml
src/common.rs
src/unix/linux/disk.rs

Small addition as I needed to get stats on a tmpfs mount which is filtered out currently.
Let me know if there's anything that needs changing or if I've missed any limitations that resulted in tmpfs mounts being filtered in the first place

Add feature flag `linux-tmpfs` to list tmpfs mounts

---

.github/workflows/CI.yml

-  replace `actions-rs/toolchain@v1` into `dtolnay/rust-toolchain@stable`
-  replace `actions-rs/cargo@v1` into `ClementTsang/cargo-action@v0.0.6`
-  upgrade `actions/checkout@v2` into `actions/checkout@v4`

ci: replace unmaintained action-rs and upgrade actions/checkout

---

.cirrus.yml
.github/workflows/CI.yml
Cargo.lock
Cargo.toml
README.md
examples/simple.rs
src/common.rs
src/debug.rs
src/unix/apple/app_store/process.rs
src/unix/apple/cpu.rs
src/unix/apple/disk.rs
src/unix/apple/macos/process.rs
src/unix/freebsd/disk.rs
src/unix/freebsd/network.rs
src/unix/freebsd/process.rs
src/unix/freebsd/system.rs
src/unix/freebsd/utils.rs
src/unix/linux/disk.rs
src/unix/linux/process.rs
src/unix/linux/system.rs
src/unix/linux/utils.rs
src/unknown/process.rs
src/windows/groups.rs
src/windows/process.rs
src/windows/sid.rs
src/windows/system.rs
src/windows/users.rs
src/windows/utils.rs
tests/process.rs

Use `OsString` for process names

---

Cargo.toml
src/common.rs
src/unix/apple/app_store/process.rs
src/unix/apple/macos/process.rs
src/unix/freebsd/process.rs
src/unix/freebsd/utils.rs
src/unix/linux/process.rs
src/unknown/process.rs
src/windows/process.rs
tests/process.rs

This continues the "os stringification" on the `Process` type where now not only the process name, but also the arguments and environment variables are also done as `OsString`, mirroring `std`.

Use `OsString` for Process Args and Env Vars

---

src/common.rs
src/lib.rs
src/utils.rs

This PR causes the bench_refresh_components benchmark to go from 1,517,282 ns/iter to 142,299 ns/iter when the "multithread" feature is enabled, which it is on by default. This massive improvement in speed is because reading from the `/sys/class/hwmon/` files in Linux can be slow. In particular reading the CPU and chipset temperatures were taking about 60 ms each on my system.

Multithreaded component refresh

---

src/lib.rs
src/unix/apple/cpu.rs
tests/cpu.rs

**Describe the bug**
Using the current latest checkout of this repo (or any 0.30.x version) on a Mac can result in `cpu.cpu_usage()` reporting a `NaN`. This is primarily caused by this code:
https://github.com/GuillaumeGomez/sysinfo/blob/b7d7f317bad003cd6053a967c668d524ab84b0b0/src/unix/apple/cpu.rs#L239-L244
If `refresh_cpu()` is called in rapid succession the collected data can be the same, resulting in `total` being 0, since `in_use` is divided by `total`, this creates a divide by zero situation and can return a NaN.
It can be worked around by waiting `sysinfo::MINIMUM_CPU_UPDATE_INTERVAL` between calls to `refresh_cpu()`, as the data will (hopefully) no longer be the same.
Some platforms, such as Linux, do this interval check internally: …

Mitigate `cpu_usage()` from returning NaN on Macs

---

src/unix/linux/component.rs
src/unix/linux/process.rs
tests/code_checkers/utils.rs

- reads file entry type instead using is_file/is_dir
- file type is checked now at the top of function to avoid unnecessary computations like `path = entry.path()`
changes are visible in flamegraph(probably no big gains, but at least helped a little in my project)

is_dir/is_file small improvements

---

src/unix/linux/component.rs

Checking to see if `/sys/class/hwmon*` is a directory fails because it is a symbol link to a directory.
Fixes #1245

/sys/class/hwmon* are not directories, they are symbolic links 

---

src/common.rs
src/unix/apple/system.rs
src/unix/freebsd/system.rs
src/unix/linux/system.rs
src/unknown/system.rs
src/windows/system.rs

Add `System::refresh_cpu_list` method

---

src/common.rs

This pull request fixes a minor typo (Archicture → Architecture).

Fix minor typo in doc comment

---

src/c_interface.rs

clippy tips:
```
error[E0308]: mismatched types
--> src/c_interface.rs:436:14
|
433 | pub extern "C" fn sysinfo_process_parent_pid(process: CProcess) -> PID {
|                                                                    --- expected `i32` because of return type
...
436 |     unsafe { (*process).parent().unwrap_or(Pid(0)).0 }
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `usize`
|
help: you can convert a `usize` to an `i32` and panic if the converted value doesn't fit
|
436 |     unsafe { (*process).parent().unwrap_or(Pid(0)).0.try_into().unwrap() }
|                                                     ++++++++++++++++++++
For more information about this error, try `rustc --explain E0308`.
```
and :
```
warning: returning the result of a `let` binding …
```

fix: cargo clippy warning and error

---

src/unix/apple/macos/component/arm.rs

#1279 
@GuillaumeGomez  @gianzellweger After some dig, I found out this is caused by multiple release of the 'service' object which get out of the maching services array, it a 'Get' call, so it should be release by CF.

Fix segfault when call calling Components::refresh_list multiple times  on M-series Mac

---

src/common/system.rs
src/unix/linux/system.rs

This PR aims at reading RSS memory information of cgroups via the `memory.stat` file.
The logic of this PR is inspired by the implementation in https://github.com/google/cadvisor/blob/1f17a6cfb8af89df396fe97c97cb5c1ec8ae6a3a/container/libcontainer/handler.go#L808.

Add support for cgroup memory.stat

---

src/common/network.rs

Fix typo in `Networks::new_with_refreshed_list()` documentation

---

src/common/system.rs
src/unix/apple/macos/system.rs
tests/process.rs

Fix invalid CPU computation when multiple calls to `refresh_process` are done in succession on macOS

---

src/unix/apple/disk.rs
src/unix/apple/ffi.rs

This PR implements a solution for #1282 by adding an Objective-C autorelease pool around the `CoreFoundation` FFI calls `sysinfo` uses to obtain disk information. This was chosen over a tempoary thread because spawning a thread is a much heavier operation (shared memory, stack allocations, etc). It also seems better then a worker thread because longer-lived apps that don't call this operation much might not want an extra thread living forever. In addition to all these approaches, if people are using `sysinfo` code in a traditional cocoa app then this thread would be extra pointless as the built-in runloops would be clearing autorelease'd values out already.
In the future this pool _could_ be moved to a more reusable context to support multiple refreshes before draining, but this is a …

Wrap Apple disk refreshing in autorelease pool to avoid system caching

---

Cargo.toml
src/common/disk.rs
src/unix/apple/disk.rs
src/unix/freebsd/disk.rs
src/unix/linux/disk.rs
src/unknown/disk.rs
src/windows/disk.rs

Add is_read_only flag on Disks, which shows whether the volume is read only. Tested under Linux, with implementations for all other platforms (other platforms not tested.)
- Implement is_read_only flag for disks on macOS, FreeBSD, Linux, and Windows
- Add is_read_only() method to the common Disk struct
- Update documentation for the new is_read_only() method
- Ensure consistent implementation across all supported platforms
This PR was written with the assistance of aider.

Add is_read_only flag for disks

---

src/common/system.rs

feat(common): fallback to std::env::consts::ARCH for System::cpu_arch

---

src/windows/users.rs
src/windows/utils.rs
tests/users.rs

fix:   #1233
pcwstr cannot be directly converted from Vec<u16>,  and direct conversion may cause loss of information.

fix(win):  user.groupps()  multiple times doesn't return the same output

---

src/unix/linux/cpu.rs
src/unix/linux/system.rs

Fixes #1351.
Can any of you confirm it fixes your issue please @M1loseph, @stormshield-fabs?

Fix CPU computation on linux processes when not all of them are refreshed at once

---

src/unix/network_helper.rs

`getifaddrs` in `get_interface_ip_networks` will return sub-interfaces with the format `<interface name>:<interface index>`, but this sub-interfaces are not presented in `/sys/class/net/`, so this sub-interfaces are skipped in  `refresh_networks_addresses`.
This PR fix this by overriding the sub-interfaces name with their parents interfaces name in `get_interface_ip_networks`.

Add support for sub-interfaces in network_helper::get_interface_ip_networks

---

src/common/network.rs
src/unix/apple/network.rs
src/unix/freebsd/network.rs
src/unix/linux/network.rs
src/unknown/network.rs
src/windows/network.rs

This PR add mtu value for `Network`. This value can be useful to understand network issue.

Add mtu information for interfaces

---

src/debug.rs
src/serde.rs

Add missing `mtu` field in `Debug` implementations and `serde`

---

src/common/system.rs

Fixes #1349.
Discovered about it [here](https://stackoverflow.com/a/64414551). The information is also available in `man proc`.

Add documentation about `DiskUsage::read_bytes` not increasing

---

Cargo.toml
src/unix/linux/disk.rs
tests/disk.rs

Remove procfs dependency and fix disk I/O test

---

src/windows/cpu.rs
src/windows/system.rs

https://github.com/GuillaumeGomez/sysinfo/issues/1381
If another program is updating the performance counters registry, CPU performance counters cannot be opened because the performance counter registry is in an invalid state.
When it happens, recreate the performance counter query at the next refresh of CPU information, adding a request to reload performance counter information from the registry (without this request, the performance counter library caches the registry data internally).

Windows: allow recovering from performance counter errors

---

Cargo.toml
src/unix/apple/cpu.rs
src/unix/apple/macos/component/x86.rs
src/unix/apple/macos/process.rs
src/unix/apple/macos/system.rs
src/unix/apple/system.rs

Closes https://github.com/GuillaumeGomez/sysinfo/issues/1392.
Libc changed the representation of `libc::vnode_info_path::vip_path`.
- https://docs.rs/libc/0.2.164/aarch64-apple-darwin/libc/struct.vnode_info_path.html
- https://docs.rs/libc/0.2.165/aarch64-apple-darwin/libc/struct.vnode_info_path.html

Deal with libc 0.2.165's removal of array size hacks

---

src/windows/cpu.rs

Fixes #1390 
This was probably caused by legacy code, the CPU frequency on windows would only be read once, which was controlled by a boolean. Since now the refresh is controlled by an externally provided CpuRefreshKind, this boolean was no longer needed, so by removing it the frequency can be refreshed whenever it is requested.

Fix Windows CPU frequency not refreshing

---

benches/basic.rs
examples/simple.c
examples/simple.rs
src/c_interface.rs
src/common/disk.rs
src/common/network.rs
src/sysinfo.h
src/unix/apple/disk.rs
src/unix/apple/network.rs
src/unix/freebsd/disk.rs
src/unix/freebsd/network.rs
src/unix/linux/disk.rs
src/unix/linux/network.rs
src/unknown/disk.rs
src/unknown/network.rs
src/windows/disk.rs
src/windows/network.rs
tests/disk.rs
tests/network.rs

Part of https://github.com/GuillaumeGomez/sysinfo/issues/1405.

Remove some refresh list

---

src/common/system.rs

Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1407.

Add missing documentation for returned value of `Process::kill` and add extra explanations

---

benches/basic.rs
examples/simple.rs
src/common/user.rs
src/lib.rs
tests/users.rs

Rename `Users::refresh_list` and `Groups::refresh_list` into `refresh`

---

src/windows/users.rs
src/windows/utils.rs

In an attempt to fix #1233, a pull request #1359 was made which introduced broken code into the repo, shown below:
```rust
#[cfg(any(feature = "user", feature = "system"))]
pub(crate) unsafe fn to_pcwstr(v: Vec<u16>) -> windows::core::PCWSTR {
if v.is_empty() {
return windows::core::PCWSTR::null();
}
let string = String::from_utf16(&v).unwrap_or_default();
// New string allocated here with format!(), but data in the HSTRING is also dropped here (tested with breakpoints)
windows::core::PCWSTR(windows::core::HSTRING::from(&format!("{}\0", string)).as_ptr())
}
```
This caused inconsistent behavior when returning groups for users, as the data in the HSTRING was freed before it could be used in the `get_groups_for_user` function. Additionally, HSTRING internals already terminate given strings …

fix(win): fix HSTRING being dropped, causing NERR_UserNotFound errors

---

src/common/system.rs

The scraped examples and existing documentation are not helpful at all in understanding how these functions relate under actual systems, e.g. understanding whether `format!("{} {}", System::name(), System::os_version())` would produce something that is meaningful. Someone might try this on Linux and get "Ubuntu 24.04" and conclude it's good, but they end up producing nonsense like "Darwin 15.1.1" and "Pixel 9 15" on other systems.

Show example outputs in System documentation

---

src/unix/apple/system.rs
src/unix/linux/system.rs

Closes https://github.com/GuillaumeGomez/sysinfo/issues/1421.

Avoid trailing whitespace and consecutive whitespace in OS versions

---

.github/workflows/CI.yml
src/unix/apple/disk.rs
src/unix/apple/macos/ffi.rs
src/unix/apple/mod.rs
src/unix/apple/system.rs
src/unix/linux/utils.rs
src/windows/process.rs
src/windows/sid.rs

```console
warning: unused variable: `processes_to_update`
--> src/unix/apple/system.rs:234:9
|
234 |         processes_to_update: ProcessesToUpdate<'_>,
|         ^^^^^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_processes_to_update`
|
= note: `#[warn(unused_variables)]` on by default
warning: field `bsd_name` is never read
--> src/unix/apple/disk.rs:28:5
|
25 | pub(crate) struct DiskInner {
|                   --------- field in this struct
...
28 |     bsd_name: Option<Vec<u8>>,
|     ^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: type alias `RetainedCFString` is never used
--> src/unix/apple/disk.rs:341:17
|
341 | pub(crate) type RetainedCFString = CFReleaser<core_foundation_sys::string::__CFString>;
|                 ^^^^^^^^^^^^^^^^ …
```

Resolve dead code warnings on various platforms

---

src/common/system.rs
src/unix/apple/macos/ffi.rs
src/unix/apple/system.rs

Identify macOS as OS X or Mac OS X on appropriate version ranges

---

src/common/system.rs
src/unix/linux/system.rs

Improve System::long_os_version() on Linux and Android

---

src/unix/linux/component.rs

In the `from_hwmon()` function, the loop should skip the entry if it is a directory, but the current code will skip the entry if it is NOT a directory. This PR just fix that logic.

Fix  wrong logic in from_hwmon() function

---

src/windows/process.rs

The ```compute_cpu_usage``` function relied on redundant operations and inefficient handling of cached system times. This could lead to unnecessary updates to system times, resulting in reduced efficiency and increased overhead.
I updated the function to use cached values unless the time elapsed since the previous values were cached exceeds MINIMUM_CPU_UPDATE_INTERVAL, ensuring system times are only refreshed when necessary. 
- Specifically minimizes the amount of calls to ```GetSystemTimes```, and ```filetime_to_u64```.
Now, after each call to ```compute_cpu_usage``` if the last time these values were retrieved ( a call to ```GetSystemTimes``` took place ) is less than MINIMUM_CPU_UPDATE_INTERVAL ( system values haven't updated ) the function will use the values used previously. …

Improve CPU usage efficiency

---

Cargo.toml
src/windows/process.rs
src/windows/system.rs

Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1450.
Happy weekend.
Rather than using `NtQueryInformationProcess` in `refresh_processes_specifics`, I use the documented WinAPI functions `CreateToolhelp32Snapshot`, `Process32FirstW`, and `Process32NextW` with `PROCESSENTRY32W` instead of some weird buffers and scary memory operations :o. This function greatly increases the safety and potential performance of the call. 
Furthermore, determining memory usage has been changed from using `SYSTEM_PROCESS_INFORMATION` to using `PROCESS_MEMORY_COUNTERS_EX`. Virtual memory usage has abnormally large values (e.g., 2205843243008 bytes). At the time of posting this draft, I'm still not sure if this is intentional, but using `PROCESS_MEMORY_COUNTERS_EX`'s `PrivateUsage` field seems to give a …

Use CreateToolhelp32Snapshot, Process32FirstW and Process32NextW

---

src/common/system.rs
src/unix/apple/system.rs
src/unix/freebsd/system.rs
src/unix/linux/system.rs
src/unknown/system.rs
src/windows/system.rs

This is similar to System::distribution_id() but for ID_LIKE. See
<https://www.freedesktop.org/software/systemd/man/latest/os-release.html#ID_LIKE=>.

Add System::distribution_id_like()

---

Cargo.toml
src/lib.rs
src/unix/apple/disk.rs
src/unix/apple/ffi.rs
src/unix/apple/macos/component/arm.rs
src/unix/apple/macos/component/x86.rs
src/unix/apple/macos/cpu.rs
src/unix/apple/macos/disk.rs
src/unix/apple/macos/ffi.rs
src/unix/apple/macos/process.rs
src/unix/apple/utils.rs

Use `objc2-core-foundation`, which is a (mostly) auto-generated version of `core-foundation-sys`.
This avoids error-prone use of `CFReleaser::new` (called `CFRetained::from_raw` in `objc2-core-foundation`) in many cases, since `objc2-core-foundation` handles that correctly according to the memory management rules. Additionally, we use the `CFString` conversions in `objc2-core-foundation` to avoid re-implementing them in this crate.

Use `objc2-core-foundation`

---

.github/workflows/CI.yml
src/unix/apple/ffi.rs
src/unix/apple/macos/ffi.rs
src/unix/apple/macos/mod.rs
src/unix/utils.rs

Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1475
Rewrites the `wait_process` cfg so that the function is available on all platforms except on iOS and macOS when the `apple-sandbox` feature is enabled.
Adds an additional CI check as requested.

Fix wait_process cfg

---

src/unix/linux/system.rs

This PR fixes an edge case where the `memory.max` file contains `max` when no limit is set for the container. If the value was `max`, the `read_u64` function would fail, causing cgroup limits to not be returned.

Fallback to u64::MAX when memory.max is not a number

---

src/unix/apple/cpu.rs
src/unix/apple/macos/cpu.rs

Hey,
the current version reports a frequency of 4 Mhz for my M4 Max.
According to https://github.com/vladkens/macmon/issues/11#issuecomment-2509396677 the meaning of the value changed for the M4 generation. This applies the same fix.
I am not sure whether this would work for a M3 Ultra (M3 in the name but  might be a more modern chip). There might be a better way to check for the intended meaning of the value.

Fix M4 frequency calculation

---

Cargo.toml
README.md
src/windows/component.rs
src/windows/cpu.rs
src/windows/disk.rs
src/windows/process.rs
src/windows/sid.rs
src/windows/system.rs
src/windows/utils.rs

Replaces and closes #1338 
Checked that all these three versions are working (0.58 had not yet used the option arguments), as in tests working. Some structs and functions are now feature gated.
Admittedly, I am not really sure what I am doing, but it seems to work. (The first test run for each version did fail for unknown reasons, a single test, often `test_wait_child`, but on the second test run it passed.)
Also bumped itertools for the sake of it. 
Edit: updated MSRV in README. I also realized that I should add the new features to the corresponding sysinfo fetures.

Bump windows to 0.59-0.61

---

Cargo.toml
src/unix/apple/disk.rs
src/unix/apple/ffi.rs
src/unix/apple/macos/component/arm.rs
src/unix/apple/macos/component/x86.rs
src/unix/apple/macos/cpu.rs
src/unix/apple/macos/disk.rs
src/unix/apple/macos/ffi.rs
src/unix/apple/macos/utils.rs

The new version of `objc2-core-foundation` moves a bunch of functions to be associated functions/methods on the relevant type instead (see first commit). This is a non-breaking change, as the functions are still available, though they've been deprecated, so you'll likely start seeing errors in CI without this fix.
Additionally, I've added a new crate `objc2-io-kit`, which contains auto-generated bindings to IOKit, which allows reducing `sysinfo`'s need for custom `ffi` declarations quite substantially.
Spiritual follow-up to https://github.com/GuillaumeGomez/sysinfo/pull/1461.

Update to `objc2-core-foundation` v0.3.1 and use `objc2-io-kit`

---

src/unix/linux/cpu.rs

In some architectures (like loongarch64), the key in `/proc/cpuinfo` is recorded in uppercase. (like: "model name" -> "Model Name" in loongarch64

feat: improve reading of cpu brand in multiple architectures

---

Cargo.toml

I believe that making the range >=0.59, <0.63 in #1532 was a mistake as windows 0.62 has not been published yet so this crate can't guarantee compatibility with it.

Reduce windows version range

---

src/unix/linux/cpu.rs

In loongarch64 machine, `/proc/cpuinfo` frequency line starts with "CPU MHz", not "cpu MHz"

fix(linux/cpu): fix `get_cpu_frequency` on loongarch64 machine

---

src/common/component.rs
src/unix/linux/component.rs

Small fix to have the label formated as documented.
I removed the temp_[id] from the first two cases, the label will get pretty long and I think it is enough data to understand what sensor is used.

fix: always format linux component labels

---

src/c_interface.rs
src/common/system.rs
src/sysinfo.h
src/unix/apple/macos/system.rs
src/unix/apple/system.rs
src/unix/freebsd/ffi.rs
src/unix/freebsd/system.rs
src/unix/linux/system.rs
src/unknown/system.rs
src/windows/ffi.rs
src/windows/mod.rs
src/windows/system.rs

This PR adds support for retrieving information from the motherboard using 4 methods: `motherboard_name`, `motherboard_vendor`, `motherboard_version` and `motherboard_serial`.
Some of the logic used to retrieve the information is inspired by [fastfetch](https://github.com/fastfetch-cli/fastfetch).
Thanks to [Squitch](https://github.com/Squitch1) for improvements ideas and for making the code work for MacOS!
Implementation details:
- On Linux, the `/sys/devices/virtual/dmi/id/{board_name, board_vendor, board_version, board_serial}` files, or for ARM systems, the `/proc/device-tree/{board, compatible}` files are used.
- On FreeBSD, the information is retrieved from the kernel environment variables `smbios.planar.product`, `smbios.planar.maker`, `smbios.planar.version` and …

feat: add support for retrieving motherboard information
