- src/linux/system.rs
> Handle processes with spaces in their name

- examples/src/simple.rs
- src/linux/process.rs
- src/linux/system.rs
- src/mac/process.rs
- src/mac/system.rs
Fixes issue #30. Note that this depends on the other PR.
> provide cmdline as a vector

- src/linux/process.rs
- src/linux/system.rs
- src/mac/process.rs
- src/mac/system.rs
> Expose uid and gid information about processes

- .travis.yml
- Cargo.toml
- src/linux/disk.rs
- src/linux/system.rs
- src/sysinfo.rs
- tests/disk_list.rs
Fixes #50.
@zhangjinpeng1987: Can you confirm it fixed your problem please?
> Fix disk getter

- Cargo.toml
- examples/src/simple.rs
- src/mac/process.rs
- src/mac/system.rs
> Mac status

- Cargo.toml
- src/linux/system.rs
> Fix overflow

- src/linux/disk.rs
- src/linux/system.rs
- src/mac/disk.rs
- src/mac/system.rs
- src/traits.rs
- src/utils.rs
this also includes a number of related cleanups and fixes, which are mostly separated into different commits
> convert Linux side of API away from String

- Cargo.toml
cc @sp3d (the new version with your changes has already been released on crates.io)
> Update crate version

- Cargo.toml
- examples/Cargo.toml
- src/linux/component.rs
- src/linux/system.rs
- src/mac/system.rs
- src/utils.rs
> Remove unwraps

- .travis.yml
- src/linux/component.rs
- src/linux/disk.rs
Fixes #99.
Can you give it a try @cGuille, please?
> Support raspberry

- README.md
- src/windows/process.rs
- src/windows/system.rs
- src/windows/tools.rs
> Win support

- README.md
- src/linux/system.rs
Fix issue https://github.com/GuillaumeGomez/sysinfo/issues/110 and added badges to `README`.
> Fix uptime

- .travis.yml
- Cargo.toml
- src/linux/component.rs
- src/linux/disk.rs
- src/linux/process.rs
- src/linux/processor.rs
- src/mac/component.rs
- src/mac/disk.rs
- src/mac/process.rs
- src/mac/processor.rs
> 32 bits fix

- Cargo.toml
- src/linux/disk.rs
> Fix invalid type error

- src/windows/process.rs
Uses `GetModuleFileNameExW` to grab root directory of module. This is kind of related to #125; I wanted to add the others too, but I'm not sure how.
> Windows: get root directory

- src/windows/process.rs
I made a mistake in the last PR: it didn't get the *root* path, it got the *exe* path. This PR corrects that and adds both.
> Windows: get exe path and correct root

- src/linux/system.rs
Fixes #143 
Can you confirm it works on your side @maciejhirsz please?
> Fix invalid CPU values in refresh_process method

- src/linux/system.rs
- src/mac/system.rs
> Use UnsafeCell instead of unsafe

- Cargo.toml
- src/system.rs
- src/windows/process.rs
- src/windows/system.rs
> Windows fixes

- src/system.rs
> Add test to check if Process implements Send and Sync traits

- Cargo.toml
> Use correct license in cargo file and update version

- src/linux/system.rs
> Handle MemFree as well

- .travis.yml
- Cargo.toml
- src/common.rs
- src/linux/system.rs
- src/mac/system.rs
- src/sysinfo.rs
- src/traits.rs
- src/windows/system.rs
Fixes #76.
cc @jonathandturner
> Refresh specifics

- Cargo.toml
- src/system.rs
- src/utils.rs
Fixes #182
Sounds good to you @tomaka ?
> change get_current_pid signature

- Cargo.toml
- src/windows/tools.rs
Fixes #191.
cc @jonathandturner @androbtech
> Fix windows

- src/mac/network.rs
> Prevent potential failure in OSX network usage computation

- src/mac/system.rs
> Update to new uninitialized api

- src/linux/component.rs
> Fix doc url

- src/linux/component.rs
Fixes #217 
@alex-dow: If you could just confirm that it solves the issue for you, that'd be awesome. I'll add #218 soon as well.
> Add specific path to get raspberry pi CPU temperature

- src/c_interface.rs
- src/common.rs
- src/linux/system.rs
- src/mac/system.rs
- src/traits.rs
- src/unknown/system.rs
- src/windows/system.rs
Fixes #218.
@alex-dow is this what you had in mind?
> More refreshes

- Cargo.toml
- src/sysinfo.rs
- src/windows/process.rs
- src/windows/processor.rs
- src/windows/system.rs
Fixes #216 
@tkozybski: Your help was really appreciated on this, thanks a lot for pointing me to this API! A few numbers:
```
=> before:
running 8 tests
test bench_new                ... bench: 597,681,058 ns/iter (+/- 520,389,224)
test bench_refresh_all        ... bench: 192,556,222 ns/iter (+/- 107,715,769)
test bench_refresh_disk_lists ... bench:     345,887 ns/iter (+/- 29,159)
test bench_refresh_disks      ... bench:     112,346 ns/iter (+/- 15,075)
test bench_refresh_network    ... bench:         203 ns/iter (+/- 14)
test bench_refresh_process    ... bench:       2,706 ns/iter (+/- 176)
test bench_refresh_processes  ... bench: 191,591,762 ns/iter (+/- 5,917,054)
test bench_refresh_system     ... bench:       2,489 ns/iter (+/- 456)
=> after:
running 8 tests
test bench_new …
```
> Greatly improve windows performance

- Cargo.toml
- src/windows/process.rs
- src/windows/system.rs
- src/windows/tools.rs
@tkozybski I added your suggestion for the process name.
Mostly disks improvements here:
```
before =>
running 8 tests
test bench_new                ... bench:  48,019,473 ns/iter (+/- 210,328,340)
test bench_refresh_all        ... bench:   1,984,283 ns/iter (+/- 258,629)
-> test bench_refresh_disk_lists ... bench:     342,007 ns/iter (+/- 46,104)
-> test bench_refresh_disks      ... bench:     113,166 ns/iter (+/- 10,406)
test bench_refresh_network    ... bench:         207 ns/iter (+/- 22)
test bench_refresh_process    ... bench:       2,730 ns/iter (+/- 213)
test bench_refresh_processes  ... bench:   1,755,207 ns/iter (+/- 150,654)
test bench_refresh_system     ... bench:       2,546 ns/iter (+/- 929)
after =>
running 8 tests
test bench_new                ... bench:  54,047,309 ns/iter …
```
> Windows improvements

- Cargo.toml
- src/windows/component.rs
- src/windows/system.rs
> Windows temperature

- src/traits.rs
Fixes #227 
cc @ignatenkobrain
> Fix doc example

- Cargo.toml
- README.md
- src/linux/disk.rs
- src/linux/process.rs
- src/linux/system.rs
- src/sysinfo.rs
New performance:
```text
test bench_new                  ... bench:  12,610,204 ns/iter (+/- 453,957)
test bench_refresh_all          ... bench:   3,339,360 ns/iter (+/- 400,590)
test bench_refresh_cpu          ... bench:      12,785 ns/iter (+/- 603)
test bench_refresh_disk_lists   ... bench:      49,465 ns/iter (+/- 3,516)
test bench_refresh_disks        ... bench:       2,288 ns/iter (+/- 21)
test bench_refresh_memory       ... bench:      11,252 ns/iter (+/- 801)
test bench_refresh_network      ... bench:      21,960 ns/iter (+/- 3,423)
test bench_refresh_process      ... bench:      20,526 ns/iter (+/- 703)
test bench_refresh_processes    ... bench:   3,069,889 ns/iter (+/- 324,993)
test bench_refresh_system       ... bench:      48,788 ns/iter (+/- 1,500)
test …
```
> Linux improvements

- benches/basic.rs
- src/linux/network.rs
- src/mac/network.rs
- src/system.rs
- src/traits.rs
- src/unknown/mod.rs
- src/unknown/network.rs
- src/windows/network.rs
Follow-up of https://github.com/GuillaumeGomez/sysinfo/pull/245
> Extend network

- README.md
Handles https://github.com/GuillaumeGomez/sysinfo/issues/246
> Document how to cross compile with proper Cargo configuration

- src/traits.rs
- src/windows/process.rs
- src/windows/system.rs
- tests/process.rs
> Enforce refresh process

- src/mac/disk.rs
- src/sysinfo.rs
- src/traits.rs
> Improve documentation

- tests/process.rs
> Update cmd tests to prevent failure in case of no network

- src/sysinfo.rs
- src/unknown/component.rs
- src/unknown/system.rs
- src/windows/component.rs
- tests/send_sync.rs
> Force implementation of Send and Sync traits on System

- src/windows/process.rs
Fixes #309 
Can you check if it solved the issue for you @VladimirMarkelov please?
> Fix compute_cpu overflow on windows

- src/mac/process.rs
Fixes #312.
Can you check if it fixes your issue @DenisKolodin please?
> Fix compute_cpu_usage underflow error on mac

- src/sysinfo.rs
Fixes #319 
Can you check if it fixes your issue @yurivict please?
> Strengthen cfg check: use linux and android instead of unix

- src/linux/disk.rs
Fixes #324.
@arctic-alpaca: Can you confirm it fixes your issue please?
> Prevent infinite recursion when getting disk

- src/linux/processor.rs
> Read cpu_frequency from scaling_cur_freq

- src/linux/processor.rs
- src/linux/system.rs
This should allow for access to individual core frequencies.
> Individual core frequency for Linux

- Cargo.toml
- src/linux/processor.rs
- src/linux/system.rs
> Fixes CPU usage computation

- Cargo.toml
- src/common.rs
- src/linux/disk.rs
> Simplify DiskType

- README.md
- src/linux/disk.rs
> Prevent infinite recursion when getting disk (part 2)

- src/mac/component.rs
Source:
https://github.com/beltex/SMCKit/blob/master/SMCKit/SMC.swift
> Renamed CPU proximity temp and added cpu die temp

- src/linux/system.rs
- src/mac/component.rs
Fixes #352.
@gnunicorn: Can you check if it fixes your issue please?
> Tasks cleanup

- Cargo.toml
- README.md
- examples/src/simple.rs
- src/sysinfo.rs
- src/traits.rs
Fixes #358.
Is it ok for you @droundy ?
> Doc improvements

- Cargo.toml
- src/linux/system.rs
- src/windows/process.rs
- tests/process.rs
Fixes #366 
@yonip23 that should your problem (if you can just confirm it, it'd be awesome!)
> Prevent CPU to be NaN

- .github/workflows/CI.yml
- Cargo.toml
- build.rs
- src/common.rs
- src/debug.rs
- src/mac/disk.m
- src/mac/disk.rs
- src/mac/ffi.rs
- src/mac/mod.rs
- src/mac/system.rs
- src/mac/users.rs
- src/mac/utils.rs
- src/sysinfo.rs
- src/utils.rs
Fixes #375.
@hippietrail: I was able to make it work, thanks for providing me the code in swift, it helped me a lot. In the end, I cheated a bit by using some objective-C code which I link when compiling sysinfo. But I was just not able to figure out how to make it work without it for the moment, which saddens me a lot...
> Greatly improve disk handling on mac

- .github/workflows/CI.yml
- src/linux/system.rs
- src/mac/system.rs
- src/sysinfo.rs
- src/traits.rs
- src/unknown/system.rs
- src/windows/system.rs
> Add System::get_name and System::get_version

- src/mac/disk.m
> UIKit for iOS, AppKit for macOS

- src/apple/component.rs
- src/apple/disk.rs
- src/apple/ffi.rs
- src/apple/ios/mod.rs
- src/apple/macos/component.rs
- src/apple/macos/disk.rs
- src/apple/macos/ffi.rs
- src/apple/macos/mod.rs
- src/apple/mod.rs
- src/apple/system.rs
@ab-cgh After taking another long look, I still had something bugging me. So I changed a bit the reexports to make the code a bit simpler. Once this is merged, I'll make a new release so you can enjoy your fixes. :)
> Clean up imports/reexports in apple module

- src/sysinfo.rs
- src/windows/system.rs
I still need to see if these variables are also available on older windows versions
> Implemented get_kernel_version & get_os_version for windows

- Cargo.toml
> Upgrade crate version to 0.15.11

- README.md
> Fix a small spelling error.

- src/windows/tools.rs
This seems to fix #426  
I've tested this by formatting a USB stick to have 3 partitions and before this it said 28GB now, 1GB for every partition, beside that the other disks i have in my pc still showed up correctly with their correct size.
> Windows use partition size instead of disk size

- Cargo.toml
- build.rs
- src/apple/macos/disk.m
- src/apple/macos/disk.rs
- src/apple/macos/ffi.rs
Part of #411.
@akaylh Does it work better with this version? I expect it to still not work but who knows...
> [mac] Rewrite get_disks function so it doesn't require external objective-C code anymore

- src/linux/system.rs
> Convert KiB from /proc/meminfo into KB

- src/apple/network.rs
- src/linux/network.rs
- src/traits.rs
- src/windows/network.rs
Fixes #438.
@feniljain: This should fix your issue.
> Prevent "Subtract Overflow" in network modules

- Cargo.toml
> Set minimum libc version to 0.2.86

- src/lib.rs
- src/linux/component.rs
- src/linux/system.rs
- src/linux/users.rs
- src/system.rs
- src/windows/component.rs
- src/windows/system.rs
- src/windows/tools.rs
I've included a regression test as well.
> Remove trailing NUL bytes from Windows hostnames

- src/apple/users.rs
- src/common.rs
- src/lib.rs
- src/linux/system.rs
- src/linux/users.rs
- src/traits.rs
- src/windows/users.rs
* Added uid/gid to User
* Updated the various os level functions to populate the new fields.
* Added test to check that uid/gid are being populated.
Fixes #167
> Add user id and group id to User

- Cargo.toml
- src/apple/ffi.rs
- src/apple/macos/ffi.rs
- src/apple/macos/process.rs
- src/apple/processor.rs
- src/apple/system.rs
- src/lib.rs
> Fix CPU computation on mac

- src/linux/system.rs
Command line does not exist for kernel process.
A more reliable approach is to fetch the process name
from the stat file, where it exists under the second string
inside parenthesis.
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>
> linux: system: Fetch process name from stat

- src/lib.rs
- src/linux/process.rs
- Add tests to make sure that values are well defined and inside range
> Improve CPU usage response values at first time

- src/lib.rs
> Add test to enforce the return value of System::refresh_process

- src/lib.rs
> Make it more clear how to use use the different information

- src/apple/macos/process.rs
- src/common.rs
- src/linux/process.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/487.
> Rework Signal enum and remove #[repr(C)] on it

- src/apple/processor.rs
- src/lib.rs
> Processors checks

- examples/src/simple.rs
- src/lib.rs
- src/windows/processor.rs
> Extend processor test

- src/linux/system.rs
- src/system.rs
> Ensure that linux uptime is computed every time in System::get_uptime

- src/traits.rs
From the discussion in #463 with @evanjs.
> Add extra information for ProcessExt::name method

- src/lib.rs
> Fix user test

- src/apple/disk.rs
- src/apple/macos/disk.rs
- src/common.rs
- src/debug.rs
- src/linux/disk.rs
- src/traits.rs
- src/unknown/disk.rs
- src/windows/disk.rs
- src/windows/tools.rs
> Rework DiskType enum

- src/linux/disk.rs
> Add support for removable disk on linux

- src/lib.rs
- src/linux/processor.rs
> Fix check_processors_number test

- tests/disk_list.rs
> Update disk test

- src/windows/system.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/534.
> Get swap memory information on Windows

- src/windows/system.rs
Fixes #539.
As mentionned in #534, `GetPerformanceInfo` should be used to get swap information.
> Fix swap computation on windows

- tests/process.rs
@ceronman: I really liked the idea of testing the environment variables you added so I extracted it.
If you prefer to have the ownership of the commit, simply open the same PR with the same changes and I'll close this one.
> Add test for environment variables

- Cargo.toml
- src/apple/macos/ffi.rs
- src/apple/macos/process.rs
- src/apple/system.rs
- tests/process.rs
Follow-up of #555.
@ceronman: I pushed here because I couldn't push on your branch directly. I squashed your commits into one and added mine on top of top to keep your contributions.
Once this PR is merged, I'll publish a new version.
Again: thanks a lot for your work!
> Add support for getting process current working directory on macOS

- src/windows/process.rs
- tests/process.rs
This adds support for getting process current working directory on Windows.
This will only work on Win64. 32 bit process require quite a bit more work. 
Note that there is a bit of code duplication between this and the code to get command line. I think this could be unified, but I think it would be better to do that in a separate PR. A lot of the same code can be reused to get the process environment variables.
Thanks!
> Add support for getting process current working directory on Windows

- src/windows/process.rs
Little cleanup following #556.
The idea here was to remove the need to fill the `RTL_USER_PROCESS_PARAMETERS[32]` structs more than once for a process. It doesn't seem to impact performance.
What do you think @ceronman ?
> Rework windows process information retrieval

- src/apple/ffi.rs
- src/apple/macos/process.rs
- src/apple/system.rs
- tests/process.rs
> Fix test on mac

- src/apple/macos/process.rs
- src/apple/network.rs
- src/lib.rs
- src/linux/process.rs
- src/linux/system.rs
- src/windows/component.rs
- src/windows/process.rs
- src/windows/system.rs
- src/windows/tools.rs
> Fix processes CPU computation on Linux

- src/windows/processor.rs
- src/windows/system.rs
- src/windows/tools.rs
This simplifies the code a fair bit, and doesn't have any downsides as far as I can tell (besides only supporting vista+, not XP, but this crate already uses vista/win7 functionality anyways).
> Use PdhAddEnglishCounter to get CPU usage.

- examples/simple.rs
- src/apple/app_store/process.rs
- src/apple/macos/process.rs
- src/linux/process.rs
- src/traits.rs
- src/unknown/process.rs
- src/windows/process.rs
> Change ProcessExt::kill API to allow finer control

- src/apple/macos/process.rs
- src/apple/system.rs
- src/common.rs
- src/lib.rs
- src/linux/process.rs
- src/linux/system.rs
- src/traits.rs
- src/unknown/system.rs
- src/windows/system.rs
> Add possibility to specify what to update in processes

- src/linux/system.rs
> Remove eprintln call and fix refresh condition

- src/apple/processor.rs
- src/apple/system.rs
- src/lib.rs
- src/linux/system.rs
- src/traits.rs
- src/windows/processor.rs
- src/windows/system.rs
- tests/network.rs
- tests/processor.rs
@ttys3 @dandavison: Can you test with this PR please?
> Only update processors if needed

- src/traits.rs
> Enforce that SystemExt implements Send and Sync

- src/apple/app_store/process.rs
- src/apple/macos/process.rs
- src/apple/system.rs
- src/linux/process.rs
- src/linux/system.rs
- src/traits.rs
- src/unknown/process.rs
- src/windows/mod.rs
- src/windows/process.rs
- src/windows/system.rs
- src/windows/utils.rs
- tests/process.rs
Part of #611.
Setting up the architecture.
> Add ProcessExt::run_time

- src/freebsd/system.rs
> FreeBSD: take ZFS ARC into account in used memory computation

- src/windows/component.rs
This PR checks the result of CoInitializeEx prior to calling CoUninitialize. According to the docs, CoUninitialize should only be called with S_OK or S_FALSE. Calling CoUninitialize when the returned value is RPC_E_CHANGED_MODE might cause heap corruption from double free or early uninitialization of some COM dependent values.
> check state of COM initialization

- src/lib.rs
@th1000s: Does it fix your problem in https://github.com/dandavison/delta/pull/869?
> Fix panic when changing the limit of open files

- src/traits.rs
As discussed in #646.
cc @th1000s
> Improve documentation for linux processes query

- src/traits.rs
Almost identical to `SystemExt::process_by_name`.
> Add  function `SystemExt::process_by_exact_name`.

- md_doc/pid.md
- src/common.rs
> Document Pid type better

- .github/workflows/CI.yml
- .gitignore
- src/common.rs
- src/system.rs
- test-unknown/Cargo.toml
- test-unknown/src/lib.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/663.
> Fix type aliases

- src/apple/macos/component.rs
- src/apple/macos/system.rs
- src/apple/processor.rs
- src/apple/users.rs
- src/apple/utils.rs
- src/freebsd/component.rs
- src/freebsd/disk.rs
- src/freebsd/processor.rs
- src/freebsd/utils.rs
- src/linux/component.rs
- src/linux/disk.rs
- src/linux/process.rs
- src/linux/processor.rs
- src/linux/utils.rs
- src/windows/component.rs
- src/windows/disk.rs
- src/windows/process.rs
- src/windows/processor.rs
- src/windows/tools.rs
- src/windows/utils.rs
- tests/code_checkers/docs.rs
- tests/code_checkers/mod.rs
> Add doc checks and fix doc issues

- src/linux/process.rs
- src/linux/system.rs
- src/windows/tools.rs
- tests/process.rs
Fixes #680.
As for the uptime vs boot time, I couldn't find a reliable source about it. Maybe I should use the uptime for boot time as well...
> Fix uptime on linux

- src/apple/macos/component.rs
- src/apple/macos/disk.rs
- src/apple/macos/process.rs
- src/apple/macos/system.rs
- src/apple/network.rs
- src/apple/processor.rs
- src/apple/system.rs
- src/apple/users.rs
- src/apple/utils.rs
- src/c_interface.rs
- src/freebsd/component.rs
- src/freebsd/system.rs
- src/freebsd/utils.rs
- src/lib.rs
- src/linux/disk.rs
- src/linux/process.rs
- src/linux/system.rs
- src/linux/utils.rs
- src/users.rs
- src/windows/component.rs
- src/windows/network.rs
- src/windows/process.rs
- src/windows/processor.rs
- src/windows/system.rs
> Fix `MaybeUninit::assume_init` calls and improve unsafe "constness"

- src/windows/tools.rs
Sometimes the call to `DeviceIoControl` can fail for unknown reasons.  This failure will prevent a drive from being visible in `System::disks()`.  So try to use a fallback to `GetDiskFreeSapceExW`.
At work I have some machines on which `System::disks()` doesn't return the full set of disks.  Here's what I see when running the `sysinfo` example:
```
Getting processes' information...
Done.
To get the commands' list, enter 'help'.
> disks
Disk("")[FS: ['N', 'T', 'F', 'S']][Type: SSD][removable: no] mounted on "C:\\": 173616594944/479509610496 B
```
The disks is missing because the call to `DeviceIoControl` returns an error (with `GetLastError` returning `1`), and disks with an unknown total disk size are ignored by `sysinfo`.  Curiously, the missing drive is also missing from things like …
> Add a fallback to get_drive_size on Windows

- src/windows/process.rs
- src/windows/system.rs
- tests/process.rs
> Fix Windows process name retrieval

- src/apple/macos/disk.rs
This PR makes a small change that avoids "duplicating disks" on macOS when the host filesystem is configured to use APFS on modern versions.
In a lot of cases, a system disk looks like this, where the disk ("Macintosh HD") is split up into many volumes via APFS:
However, `statfs` is, IMO, dumb about this. Or at least it is because of Apple's implementation of the function. When listing disk via `SystemExt::disks`, both the snapshot and the true data partition appear in the list. Other than flags, some reserved bytes (which are too risky to use as a check), `f_mntonname`, and `f_mntfromname`, they are absolutely identical. This means that while they actually point to the same underlying disk, the APIs report them as different "disks" because of the mount points differing.
To resolve this …
> macOS: Ignore non-root drive partitions

- src/traits.rs
To prevent issues like in #721.
> Improve `refresh_cpu` documentation

- src/apple/macos/process.rs
- src/freebsd/process.rs
- src/freebsd/system.rs
- tests/process.rs
> Fix System::refresh_process returned value on macOS and FreeBSD

- src/apple/processor.rs
- src/apple/system.rs
- src/common.rs
- src/freebsd/processor.rs
- src/freebsd/system.rs
- src/freebsd/utils.rs
- src/lib.rs
- src/linux/system.rs
- src/traits.rs
- src/unknown/system.rs
- src/windows/processor.rs
- src/windows/system.rs
- src/windows/tools.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/732.
The code doesn't look great after this feature change though...
cc @piec
> Create new CpuRefreshKind type, allowing to not retrieve frequency information

- Cargo.toml
> Add missing feature on winapi

- src/apple/macos/process.rs
> Fix path retrieval on mac

- src/lib.rs
- src/windows/system.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/761.
> Fix Windows CPU computation

- src/apple/macos/process.rs
- src/apple/system.rs
- src/freebsd/process.rs
- src/freebsd/system.rs
- src/lib.rs
> Fix System::refresh_processes

- src/c_interface.rs
> Fix invalid cast for C interface

- src/apple/macos/disk.rs
> Fix memory leak on mac for disk API

- src/apple/system.rs
> fix: other operation priorities fix

- src/apple/system.rs
- src/freebsd/system.rs
- src/linux/system.rs
- src/traits.rs
- src/unknown/system.rs
- src/windows/system.rs
> Add SystemExt::sort_disks_by

- src/freebsd/process.rs
- src/linux/process.rs
- src/linux/system.rs
- src/linux/utils.rs
> Correctly handle when a PID owner changes on linux and freebsd

- src/apple/macos/process.rs
> Correctly handle when a PID owner changes on macOS

- src/windows/system.rs
Functions `os_name()` and `long_os_name()` output "Windows 10"
despite running on Windows 11. 
Looking into "currentBuildVersion" since those of Windows 11 start from "22000".
cf. #654
> Show Windows 11 OS according to the build number

- src/linux/process.rs
Little optionnal cleanup. Took the liberty to change the return type, may also sprinkle some: `ok_or(())`.
> Retire unwrap_or_return in favor of try.

- src/lib.rs
- src/linux/process.rs
> Fix linux proc info retrieval

- README.md
This PR fixes a small typo which I noticed while reading through the README.
Greetings!
> README.md: Fix a small typo

- src/linux/process.rs
- src/linux/utils.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/837.
> Improve Path handling in `retrieve_all_new_process_info` function

- src/linux/cpu.rs
- src/linux/system.rs
- src/linux/utils.rs
> Move CPU-related code into cpu.rs file for linux

- README.md
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/866.
> Add an entry about good practice

- src/apple/app_store/process.rs
- src/apple/macos/process.rs
- src/common.rs
- src/freebsd/process.rs
- src/linux/process.rs
- src/linux/system.rs
- src/traits.rs
- src/unknown/process.rs
- src/windows/process.rs
- tests/process.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/858
Note: This is incomplete and will update in sometime.
> Add wait() to process

- md_doc/pid.md
- src/apple/app_store/process.rs
- src/apple/macos/process.rs
- src/freebsd/process.rs
- src/linux/process.rs
- src/traits.rs
- src/unknown/process.rs
- src/windows/process.rs
- tests/process.rs
> Add ProcessExt::session_id

- src/common.rs
> Implement TryFrom<usize> and FromStr for Gid and Uid types and TryFrom<usize> for Pid

- examples/simple.rs
- src/linux/cpu.rs
- src/linux/process.rs
- tests/code_checkers/docs.rs
- tests/code_checkers/headers.rs
- tests/process.rs
> Fix truncated environment

- Cargo.toml
- examples/simple.rs
- src/apple/network.rs
- src/common.rs
- src/freebsd/network.rs
- src/lib.rs
- src/linux/network.rs
- src/network.rs
- src/network_helper_nix.rs
- src/network_helper_win.rs
- src/traits.rs
- src/unknown/network.rs
- src/windows/network.rs
Not sure why but the "squash and merge" action of github did some really strange things for https://github.com/GuillaumeGomez/sysinfo/pull/885...
> Add MAC address to NetworkExt

- src/apple/macos/process.rs
- src/apple/macos/system.rs
- src/linux/cpu.rs
- src/linux/system.rs
- src/system.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/898.
cc @umanwizard
> Fix consecutive CPU usage updates

- src/apple/cpu.rs
- src/apple/macos/process.rs
- src/system.rs
- tests/process.rs
> Fix mac process CPU usage

- src/windows/system.rs
- src/windows/utils.rs
> Fix missing deallocation for RegOpenKeyExW

- README.md
- src/c_interface.rs
- src/lib.rs
- src/linux/component.rs
- src/linux/cpu.rs
- src/linux/system.rs
- src/network_helper_nix.rs
- src/system.rs
- src/traits.rs
- src/utils.rs
- src/windows/cpu.rs
- src/windows/process.rs
> Documentation improvements

- src/common.rs
- src/linux/process.rs
> Handle Idle state in `ProcessStatus` on linux

- src/lib.rs
- src/users.rs
Fixes the bug uncovered in https://github.com/GuillaumeGomez/sysinfo/pull/930.
> Keep all users, even fake ones on UNIX targets

- .github/workflows/CI.yml
- examples/simple.c
- src/c_interface.rs
- src/sysinfo.h
- Update sysinfo.h
- Update simple.c
- Build the C side of the example in CI by using `make` instead of just `cargo build`
- Add an explicit `drop` to address a warning.
> Bring C example up to date with current API

- .github/workflows/CI.yml
- Cargo.toml
- md_doc/serde.md
- src/lib.rs
- src/serde.rs
- tests/code_checkers/utils.rs
This is a take over of #926 (the first commits come from it).
> Serde implementation

- src/linux/process.rs
- src/linux/system.rs
- tests/process.rs
* fixed name of tasks
* fixed cpu usage of tasks not being calculated
* added test on tasks
> Fix name and cpu usage calculation of tasks of processes in Linux

- src/apple/cpu.rs
> Fix overflow on macOS

- src/linux/cpu.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/945.
Can you confirm it fixes the issue for you too @rgwood please?
> Fix CPU computation usage in linux

- src/apple/system.rs
Fixes #948.
@gianzellweger: If you could confirm it fixes the issue for you before I make a release?
> Fix used memory computation on mac and improve available memory computation

- src/linux/process.rs
- src/windows/process.rs
> Fix potential windows panic when getting process data

- tests/process.rs
> Strenghten test `test_wait_non_child`

- src/windows/system.rs
Fixes #968.
See #968: CPU time is seemingly broken in Windows 11, idle time seems to work fine tho.
> Fix windows core load: use 100 - idle_time

- src/users.rs
Found a segmentation fault when calling `System::new()` in multiple unit tests in an environment with 16+ cpu cores.
The stack trace points to getgrgid which isn't thread safe.  This PR replaces getgrgid with getgrgid_r which is thread safe.
```
(lldb) bt
* thread #111, name = 'c2::service::te', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
* frame #0: 0x00007ffff7383832 xxx-3371768afabdc658`realloc [inlined] a_crash at atomic_arch.h:108:2
frame #1: 0x00007ffff7383832 xxx-3371768afabdc658`realloc at malloc.c:406:34
frame #2: 0x00007ffff739259f xxx-3371768afabdc658`getdelim at getdelim.c:38:10
frame #3: 0x00007ffff7386d36 xxx-3371768afabdc658`__getgrent_a at getgrent_a.c:20:10
frame #4: 0x00007ffff739142d xxx-3371768afabdc658`__getgr_a at getgr_a.c:35:16
frame #5: …
```
> Use getgrgid_r instead of getgrgid for thread safety

- src/traits.rs
> Improve code examples

- md_doc/serde.md
> Fix serde doc example

- Cargo.lock
- examples/simple.rs
- src/apple/cpu.rs
- src/apple/macos/ffi.rs
- src/apple/system.rs
- src/apple/utils.rs
Part of https://github.com/GuillaumeGomez/sysinfo/issues/738.
> Move CPU-related code into cpu.rs file for macOS

- src/freebsd/cpu.rs
- src/freebsd/system.rs
- src/freebsd/utils.rs
> Move CPU-related code into cpu.rs file for freebsd

- md_doc/user.md
- src/apple/mod.rs
- src/apple/users.rs
- src/common.rs
- src/debug.rs
- src/freebsd/mod.rs
- src/lib.rs
- src/linux/mod.rs
- src/serde.rs
- src/traits.rs
- src/unknown/mod.rs
- src/unknown/users.rs
- src/users.rs
- src/windows/mod.rs
- src/windows/users.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1035.
> Improve `Group` API

- src/apple/macos/process.rs
- src/apple/macos/system.rs
- src/freebsd/cpu.rs
- src/freebsd/system.rs
- src/linux/process.rs
- src/linux/system.rs
- src/windows/cpu.rs
- src/windows/process.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1039.
> Add missing `saturating_*` calls

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/apple/macos/process.rs
- src/apple/macos/system.rs
- src/freebsd/system.rs
- src/linux/component.rs
- src/linux/process.rs
- src/linux/system.rs
- src/windows/cpu.rs
- src/windows/process.rs
Backport of #1040 and of #1041.
> Backport #1040 and #1041 to 0.29 branch

- src/linux/system.rs
As discussed in #1054 , there is an issue that occurs when the cgroups memory limits are higher than the actual system memory amount. The cgroups value is used instead, even though that amount of memory is not actually available. The solution is to use the minimum value of the total memory reported by /proc/meminfo and the cgroups value. The easiest way to accomplish this is to hoist the cgroups checks out of the `read_table` call; this was needlessly invoking the cgroups logics once per line in the meminfo table. By moving it out of the call we do it once, after the table has been processed, and we can properly consider which value we actually want to use.  Most of the changes here are whitespace; the new logic is on lines 290 and 313 (using the minimum of the mem_total and the cgroups …
> Fix memory limits to only use cgroups values if they're sensible

- README.md
- benches/basic.rs
- examples/simple.rs
- src/c_interface.rs
- src/common.rs
- src/debug.rs
- src/serde.rs
- src/traits.rs
- src/unix/apple/network.rs
- src/unix/apple/system.rs
- src/unix/freebsd/network.rs
- src/unix/freebsd/system.rs
- src/unix/linux/network.rs
- src/unix/linux/system.rs
- src/unknown/network.rs
- src/unknown/system.rs
- src/windows/network.rs
- src/windows/system.rs
- tests/network.rs
> Extract `Networks` from `System`

- README.md
- benches/basic.rs
- examples/simple.rs
- src/c_interface.rs
- src/common.rs
- src/debug.rs
- src/serde.rs
- src/sysinfo.h
- src/traits.rs
- src/unix/apple/disk.rs
- src/unix/apple/system.rs
- src/unix/freebsd/disk.rs
- src/unix/freebsd/system.rs
- src/unix/linux/disk.rs
- src/unix/linux/system.rs
- src/unknown/disk.rs
- src/unknown/system.rs
- src/windows/disk.rs
- src/windows/system.rs
- tests/disk_list.rs
> Extract `Disks` from `System`

- README.md
- benches/basic.rs
- examples/simple.c
- examples/simple.rs
- md_doc/components.md
- src/c_interface.rs
- src/common.rs
- src/debug.rs
- src/lib.rs
- src/serde.rs
- src/sysinfo.h
- src/traits.rs
- src/unix/apple/app_store/component.rs
- src/unix/apple/macos/component/arm.rs
- src/unix/apple/macos/component/x86.rs
- src/unix/apple/mod.rs
- src/unix/apple/system.rs
- src/unix/freebsd/component.rs
- src/unix/freebsd/cpu.rs
- src/unix/freebsd/mod.rs
- src/unix/freebsd/system.rs
- src/unix/linux/component.rs
- src/unix/linux/mod.rs
- src/unix/linux/system.rs
- src/unknown/component.rs
- src/unknown/mod.rs
- src/unknown/system.rs
- src/windows/component.rs
- src/windows/mod.rs
- src/windows/system.rs
Part of https://github.com/GuillaumeGomez/sysinfo/issues/1063.
> Extract `Components` from `System`

- src/unix/apple/cpu.rs
- src/unix/freebsd/cpu.rs
- src/unix/linux/cpu.rs
- src/windows/cpu.rs
- src/windows/tools.rs
- tests/cpu.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1073.
> Fix invalid name retrieval for linux CPU and remove frequency, brand and vendor ID from global CPU

- src/serde.rs
Follow-up of https://github.com/GuillaumeGomez/sysinfo/pull/1070.
> Fix `serialize_struct` field count and add a comment to prevent forgetting about it again

- benches/basic.rs
- examples/simple.rs
- md_doc/user.md
- src/common.rs
- src/debug.rs
- src/lib.rs
- src/serde.rs
- src/traits.rs
- src/unix/apple/mod.rs
- src/unix/apple/system.rs
- src/unix/apple/users.rs
- src/unix/freebsd/mod.rs
- src/unix/freebsd/system.rs
- src/unix/linux/mod.rs
- src/unix/linux/system.rs
- src/unix/users.rs
- src/unknown/mod.rs
- src/unknown/system.rs
- src/unknown/users.rs
- src/windows/mod.rs
- src/windows/system.rs
- src/windows/users.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1063.
> Separate Users from System

- benches/basic.rs
- md_doc/disk.md
- src/common.rs
- src/debug.rs
- src/lib.rs
- src/serde.rs
- src/traits.rs
- src/unix/apple/disk.rs
- src/unix/apple/mod.rs
- src/unix/freebsd/disk.rs
- src/unix/freebsd/mod.rs
- src/unix/linux/disk.rs
- src/unix/linux/mod.rs
- src/unknown/disk.rs
- src/unknown/mod.rs
- src/windows/disk.rs
- src/windows/mod.rs
Part of https://github.com/GuillaumeGomez/sysinfo/issues/1088.
> Remove DiskExt trait

- src/unix/apple/macos/process.rs
- src/unix/utils.rs
> Correctly retrieve process root directory on mac

- README.md
- benches/basic.rs
- examples/simple.rs
- src/common.rs
- src/lib.rs
- src/unix/apple/app_store/component.rs
- src/unix/apple/disk.rs
- src/unix/apple/macos/component/arm.rs
- src/unix/apple/macos/component/x86.rs
- src/unix/freebsd/component.rs
- src/unix/freebsd/disk.rs
- src/unix/linux/component.rs
- src/unix/linux/disk.rs
- src/unknown/component.rs
- src/unknown/disk.rs
- src/windows/component.rs
- src/windows/disk.rs
- tests/disk_list.rs
Part of https://github.com/GuillaumeGomez/sysinfo/issues/1080.
> Remove `sort_by` methods and rename getters into `list` and `list_mut`

- src/serde.rs
> Add missing serde implementations

- src/common.rs
> Implement Display for DiskKind

- CHANGELOG.md
- src/lib.rs
- src/unix/linux/component.rs
I fixed some typos that I found with [`typos`](https://github.com/crate-ci/typos).
> Fixed typos

- src/common.rs
> Improve doc comment formatting

- .cirrus.yml
- .github/workflows/CI.yml
- Cargo.toml
- src/common.rs
- src/lib.rs
- src/unix/apple/system.rs
- src/unix/freebsd/cpu.rs
- src/unix/freebsd/system.rs
- src/unix/linux/system.rs
- src/unknown/system.rs
- src/windows/system.rs
- tests/cpu.rs
All in one commit of CPU architecture info
> Add CPU architecture info

- src/common.rs
> Improve `load_average` documentation

- src/common.rs
- src/lib.rs
- src/unix/apple/macos/process.rs
- src/unix/freebsd/process.rs
- src/unix/freebsd/system.rs
- src/unix/linux/process.rs
- src/windows/process.rs
- tests/process.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/840.
> Add `UpdateKind` enum

- src/c_interface.rs
- src/common.rs
- src/sysinfo.h
- src/unix/apple/system.rs
- src/unix/linux/process.rs
- src/unix/linux/system.rs
- src/utils.rs
- tests/process.rs
It allows to simplify the handling of processes in linux while also improving parallel computations.
> Inline tasks at the same level as other processes

- src/common.rs
- src/lib.rs
- src/serde.rs
- src/unix/linux/process.rs
> Add `Process::thread_kind` API

- Cargo.lock
- Cargo.toml
> optimize dependency stack by removing duplications

- src/windows/process.rs
- src/windows/system.rs
Fix build errors introduced in #1185.
> Fix windows build

- src/windows/system.rs
> src/windows/system.rs: fix misaligned read

- tests/components.rs
> Add regression test for components

- .github/workflows/CI.yml
- src/unix/freebsd/network.rs
Backport of https://github.com/GuillaumeGomez/sysinfo/pull/1269.
> Backport of #1269

- Cargo.lock
- src/common/component.rs
- src/common/disk.rs
- src/common/mod.rs
- src/common/network.rs
- src/common/system.rs
- src/common/user.rs
- src/lib.rs
- src/unix/apple/groups.rs
- src/unix/apple/network.rs
- src/unix/freebsd/network.rs
- src/unix/groups.rs
- src/unix/linux/network.rs
- src/unix/network_helper.rs
- src/unknown/network.rs
- src/windows/groups.rs
- src/windows/network.rs
- src/windows/network_helper.rs
- src/windows/users.rs
- tests/code_checkers/docs.rs
> Split `common.rs` into multiple sub-files

- src/windows/cpu.rs
- src/windows/system.rs
> Fix CPU arch retrieval on Windows

- .cirrus.yml
- .github/workflows/CI.yml
- Cargo.lock
- Cargo.toml
- src/common/mod.rs
- src/common/system.rs
- src/debug.rs
- src/lib.rs
- src/macros.rs
- src/serde.rs
- src/unix/apple/ffi.rs
- src/unix/apple/macos/ffi.rs
- src/unix/apple/macos/mod.rs
- src/unix/apple/macos/utils.rs
- src/unix/apple/mod.rs
- src/unix/apple/utils.rs
- src/unix/freebsd/disk.rs
- src/unix/freebsd/mod.rs
- src/unix/linux/mod.rs
- src/unix/mod.rs
- src/unknown/mod.rs
- src/windows/mod.rs
- src/windows/utils.rs
- tests/disk_list.rs
Part of https://github.com/GuillaumeGomez/sysinfo/issues/965.
> Add `disk` feature

- .cirrus.yml
- .github/workflows/CI.yml
- Cargo.toml
- benches/basic.rs
- src/common/mod.rs
- src/debug.rs
- src/lib.rs
- src/serde.rs
- src/unix/apple/app_store/mod.rs
- src/unix/apple/ffi.rs
- src/unix/apple/ios.rs
- src/unix/apple/macos/ffi.rs
- src/unix/apple/macos/mod.rs
- src/unix/apple/mod.rs
- src/unix/freebsd/mod.rs
- src/unix/freebsd/utils.rs
- src/unix/linux/mod.rs
- src/unknown/mod.rs
- src/utils.rs
- src/windows/mod.rs
- tests/components.rs
Part of https://github.com/GuillaumeGomez/sysinfo/issues/965.
> Add `component` feature

- .cirrus.yml
- .github/workflows/CI.yml
- Cargo.toml
- benches/basic.rs
- src/common/mod.rs
- src/debug.rs
- src/lib.rs
- src/serde.rs
- src/unix/apple/mod.rs
- src/unix/freebsd/mod.rs
- src/unix/freebsd/utils.rs
- src/unix/linux/mod.rs
- src/unix/mod.rs
- src/unknown/mod.rs
- src/windows/mod.rs
- tests/network.rs
Part of https://github.com/GuillaumeGomez/sysinfo/issues/965.
> Add `network` feature

- src/common/system.rs
add comment for the usage of Process::cmd(&self)
> fix cmd usage of granting admin privileges

- src/windows/process.rs
> Fix Windows WoW64 process parent refreshing

- Cargo.toml
New take of https://github.com/GuillaumeGomez/sysinfo/pull/1295.
> Adopt windows version range >=0.54, <=0.57

- src/unix/linux/component.rs
https://github.com/GuillaumeGomez/sysinfo/pull/827 broke temperature on raspberry-pi
fix https://github.com/GuillaumeGomez/sysinfo/issues/327
> feat: support Raspberry Pi

- benches/basic.rs
- examples/simple.rs
- src/c_interface.rs
- src/common/system.rs
- src/unix/apple/app_store/process.rs
- src/unix/apple/macos/process.rs
- src/unix/apple/system.rs
- src/unix/freebsd/process.rs
- src/unix/freebsd/system.rs
- src/unix/linux/process.rs
- src/unix/linux/system.rs
- src/unknown/process.rs
- src/unknown/system.rs
- src/windows/process.rs
- src/windows/system.rs
- tests/process.rs
- tests/system.rs
> Update `System::refresh_processes` API to give control over when to remove dead processes

- src/unix/apple/network.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1378.
> Fix network data information being limited to 32 bits on mac

- src/windows/component.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/365.
> Improve components retrieval on Windows

- .github/workflows/CI.yml
I am not sure if you would want this in the CI or if it's too weird, but this is what I used to validate #1398 while working on that PR.
> Test that all source files are covered by rustfmt

- src/common/component.rs
- src/debug.rs
- src/unix/apple/app_store/component.rs
- src/unix/apple/macos/component/arm.rs
- src/unix/apple/macos/component/x86.rs
- src/unix/freebsd/component.rs
- src/unix/linux/component.rs
- src/unknown/component.rs
- src/windows/component.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1409.
> Make `Component::temperature` and `Component::max` return `Option`

- src/common/system.rs
- src/unix/apple/app_store/process.rs
- src/unix/apple/macos/process.rs
- src/unix/freebsd/process.rs
- src/unix/linux/process.rs
- src/unix/utils.rs
- src/unknown/process.rs
- src/windows/process.rs
Part of https://github.com/GuillaumeGomez/sysinfo/issues/1415.
> Make `Process::wait` return `Option<ExitStatus>`

- src/common/disk.rs
- src/common/network.rs
- src/common/system.rs
> Implement `Hash` trait on `DiskKind`, `MacAddr`, `Signal` and on `ProcessStatus`

- src/common/network.rs
- src/lib.rs
> Implement `FromStr` for `IpNetwork` and `MacAddr`

- Cargo.toml
- src/common/disk.rs
- src/common/network.rs
- src/common/system.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1442.
> Implement `Deserialize` on `DiskKind`, `MacAddr`, `IpNetwork`, `Signal`, `ProcessStatus` and `ThreadKind`

- src/unix/apple/disk.rs
- src/unix/freebsd/disk.rs
- src/unix/linux/disk.rs
- src/windows/disk.rs
> Fix disk listing

- src/common/system.rs
- src/unix/apple/app_store/process.rs
- src/unix/apple/macos/process.rs
- src/unix/freebsd/process.rs
- src/unix/linux/process.rs
- src/unknown/process.rs
- src/windows/process.rs
- tests/process.rs
> Add `Process::exists` method

- src/unix/linux/process.rs
- src/windows/process.rs
> Improve linux code to update processes

- src/common/system.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1417.
> Add `System::kernel_long_version`

- examples/simple.rs
- src/common/system.rs
- src/unix/apple/ffi.rs
- src/unix/apple/process.rs
- src/unix/freebsd/disk.rs
- src/unix/freebsd/ffi.rs
- src/unix/freebsd/mod.rs
- src/unix/freebsd/process.rs
- src/unix/linux/process.rs
- src/unix/linux/utils.rs
- src/unknown/process.rs
- src/windows/process.rs
- tests/process.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1202.
For now only supports linux.
> Add `Process::open_files` and `Process::open_files_limit`

- src/unix/freebsd/system.rs
Hello,
On our FreeBSD-based system we get a lot of warnings related to "bsd.seeotheruids" privilege when getting cpu and memory info for our process.
This patch fixes this by giving the argument `KERN_PROC_PID` instead of `KERN_PROC_PROC` to `kvm_getprocs()` in the case we want to refresh a single process. We also return early if there is no process to refresh.
> FreeBSD: improve `refresh_procs` for the single process case

- .cirrus.yml
- .github/workflows/CI.yml
- Cargo.toml
- src/unix/linux/cpu.rs
- src/unix/linux/process.rs
> Disable `multithread` feature by default

- src/unix/apple/macos/process.rs
- src/unix/apple/system.rs
- tests/process.rs
> Fix macOS issue where a removed process was still listed

- examples/simple.rs
- src/unix/freebsd/process.rs
- src/unix/freebsd/system.rs
> Fix segfault on FreeBSD

- src/windows/system.rs
Originally introduced in #1451, in windows, when retrieving process info using `CreateToolhelp32Snapshot`, the function returns a `HANDLE` that must be closed once used. This is not being done and it causes a memory leak and eventual memory exhaustion in the process. This PR creates an `Owned` object which automatically calls close at the end of the scope.
> Create an owned handle for snapshot

- md_doc/pid.md
> fix Update pid.md

- .gitignore
> fix Update .gitignore

- src/common/disk.rs
- src/unix/apple/disk.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1496.
> Enforce `Disks` implement `Send`

- src/unix/linux/disk.rs
ref: https://help.ubuntu.com/community/Autofs
> feat: ignore autofs as netdev

- src/unix/linux/cpu.rs
Fixes #1511.
@troelsarvin: Can you confirm it fixes your crash please?
> Correctly handle when new CPUs are added on linux

- README.md
- src/lib.rs
- src/unix/linux/component.rs
- src/windows/sid.rs
- tests/process.rs
- tests/system.rs
> Check more thermal zones on linux (raspberry pi)

- src/common/system.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1150.
> Mention that CPU information might not be available on Android

- src/common/system.rs
- src/lib.rs
Part of https://github.com/GuillaumeGomez/sysinfo/issues/1415.
> Add new `Process::kill_and_wait` and `Process::kill_with_and_wait` methods

- src/windows/process.rs
Part of https://github.com/GuillaumeGomez/sysinfo/issues/1415.
> Improve `Process::wait` code on Windows

- src/windows/groups.rs
Part of #1477.
It doesn't fix the issue but I saw it is recommended to use this function as it's faster than `NetGroupEnum`.
> Improve group retrieval code in Windows

- tests/users.rs
> Add test for `Groups`

- CHANGELOG.md
- README.md
- src/unix/apple/disk.rs
- src/unix/linux/process.rs
- src/windows/process.rs
- tests/process.rs
- tests/system.rs
Noticed a small typo in the README so I decided to run [typos](https://github.com/crate-ci/typos) on the repo and found some more
Cheers :)
> Fix some typos

- src/unix/linux/cpu.rs
Fixes https://github.com/GuillaumeGomez/sysinfo/issues/1527.
> Fix retrieval of CPU when information is missing on Linux

- src/common/system.rs
- src/unix/linux/process.rs
- src/windows/process.rs
- tests/process.rs
> Fix `Process::wait` on Windows and improve it on Linux/Android

- src/lib.rs
- src/unix/apple/macos/component/arm.rs
> Make macOS ARM `Components` implement `Send` and `Sync`

- src/unix/linux/cpu.rs
Fixes #1556.
Can you confirm it fixes your issue @zigazajc007?
> Improve processors CPU usage computation on linux

- src/common/system.rs
- src/serde.rs
- src/unix/users.rs
- src/windows/disk.rs
> Fix invalid serde serialization for processes name

- src/common/system.rs
> Improve documentation of `System::refresh_cpu_all`

- src/common/system.rs
Similar to https://github.com/GuillaumeGomez/sysinfo/pull/1581.
> Improve documentation of `System::refresh_cpu_specifics`
